#include <stdint.h>

#if 0
C:/msys64/home/sydlu/CProjects/clustered-forward-demo-vk/demo/calc_grid_offsets.comp
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 109

                              Capability Shader
                              Capability ImageBuffer
                              Capability StorageImageExtendedFormats
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint GLCompute 4  "main" 10
                              ExecutionMode 4 LocalSize 16 16 1
                              Source GLSL 450
                              Name 4  "main"
                              Name 10  "gl_GlobalInvocationID"
                              Name 28  "UBO"
                              MemberName 28(UBO) 0  "view"
                              MemberName 28(UBO) 1  "normal"
                              MemberName 28(UBO) 2  "model"
                              MemberName 28(UBO) 3  "projection_clip"
                              MemberName 28(UBO) 4  "tile_size"
                              MemberName 28(UBO) 5  "grid_dim"
                              MemberName 28(UBO) 6  "cam_pos"
                              MemberName 28(UBO) 7  "cam_far"
                              MemberName 28(UBO) 8  "resolution"
                              MemberName 28(UBO) 9  "num_lights"
                              Name 30  "ubo_in"
                              Name 50  "grid_idx"
                              Name 70  "light_count"
                              Name 73  "grid_light_counts"
                              Name 83  "offset"
                              Name 84  "grid_light_count_total"
                              Name 95  "grid_light_count_offsets"
                              Name 103  "grid_flags"
                              Decorate 10(gl_GlobalInvocationID) BuiltIn GlobalInvocationId
                              MemberDecorate 28(UBO) 0 ColMajor
                              MemberDecorate 28(UBO) 0 Offset 0
                              MemberDecorate 28(UBO) 0 MatrixStride 16
                              MemberDecorate 28(UBO) 1 ColMajor
                              MemberDecorate 28(UBO) 1 Offset 64
                              MemberDecorate 28(UBO) 1 MatrixStride 16
                              MemberDecorate 28(UBO) 2 ColMajor
                              MemberDecorate 28(UBO) 2 Offset 128
                              MemberDecorate 28(UBO) 2 MatrixStride 16
                              MemberDecorate 28(UBO) 3 ColMajor
                              MemberDecorate 28(UBO) 3 Offset 192
                              MemberDecorate 28(UBO) 3 MatrixStride 16
                              MemberDecorate 28(UBO) 4 Offset 256
                              MemberDecorate 28(UBO) 5 Offset 264
                              MemberDecorate 28(UBO) 6 Offset 272
                              MemberDecorate 28(UBO) 7 Offset 284
                              MemberDecorate 28(UBO) 8 Offset 288
                              MemberDecorate 28(UBO) 9 Offset 296
                              Decorate 28(UBO) Block
                              Decorate 30(ubo_in) DescriptorSet 0
                              Decorate 30(ubo_in) Binding 0
                              Decorate 73(grid_light_counts) DescriptorSet 1
                              Decorate 73(grid_light_counts) Binding 2
                              Decorate 84(grid_light_count_total) DescriptorSet 1
                              Decorate 84(grid_light_count_total) Binding 3
                              Decorate 95(grid_light_count_offsets) DescriptorSet 1
                              Decorate 95(grid_light_count_offsets) Binding 4
                              Decorate 103(grid_flags) DescriptorSet 1
                              Decorate 103(grid_flags) Binding 0
                              Decorate 108 BuiltIn WorkgroupSize
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeBool
               7:             TypeInt 32 0
               8:             TypeVector 7(int) 3
               9:             TypePointer Input 8(ivec3)
10(gl_GlobalInvocationID):      9(ptr) Variable Input
              11:      7(int) Constant 2
              12:             TypePointer Input 7(int)
              15:      7(int) Constant 256
              19:      7(int) Constant 0
              22:             TypeFloat 32
              23:             TypeVector 22(float) 4
              24:             TypeMatrix 23(fvec4) 4
              25:             TypeVector 22(float) 2
              26:             TypeVector 7(int) 2
              27:             TypeVector 22(float) 3
         28(UBO):             TypeStruct 24 24 24 24 25(fvec2) 26(ivec2) 27(fvec3) 22(float) 25(fvec2) 7(int)
              29:             TypePointer Uniform 28(UBO)
      30(ubo_in):     29(ptr) Variable Uniform
              31:             TypeInt 32 1
              32:     31(int) Constant 5
              33:             TypePointer Uniform 7(int)
              40:      7(int) Constant 1
              49:             TypePointer Function 31(int)
              69:             TypePointer Function 7(int)
              71:             TypeImage 7(int) Buffer nonsampled format:R32ui
              72:             TypePointer UniformConstant 71
73(grid_light_counts):     72(ptr) Variable UniformConstant
              76:             TypeVector 7(int) 4
84(grid_light_count_total):     72(ptr) Variable UniformConstant
              85:     31(int) Constant 0
              87:             TypePointer Image 7(int)
              91:      7(int) Constant 1048576
95(grid_light_count_offsets):     72(ptr) Variable UniformConstant
             101:             TypeImage 7(int) Buffer nonsampled format:R8ui
             102:             TypePointer UniformConstant 101
 103(grid_flags):    102(ptr) Variable UniformConstant
             106:   76(ivec4) ConstantComposite 19 19 19 19
             107:      7(int) Constant 16
             108:    8(ivec3) ConstantComposite 107 107 40
         4(main):           2 Function None 3
               5:             Label
    50(grid_idx):     49(ptr) Variable Function
 70(light_count):     69(ptr) Variable Function
      83(offset):     69(ptr) Variable Function
              13:     12(ptr) AccessChain 10(gl_GlobalInvocationID) 11
              14:      7(int) Load 13
              16:     6(bool) ULessThan 14 15
                              SelectionMerge 18 None
                              BranchConditional 16 17 18
              17:               Label
              20:     12(ptr)   AccessChain 10(gl_GlobalInvocationID) 19
              21:      7(int)   Load 20
              34:     33(ptr)   AccessChain 30(ubo_in) 32 19
              35:      7(int)   Load 34
              36:     6(bool)   ULessThan 21 35
                                Branch 18
              18:             Label
              37:     6(bool) Phi 16 5 36 17
                              SelectionMerge 39 None
                              BranchConditional 37 38 39
              38:               Label
              41:     12(ptr)   AccessChain 10(gl_GlobalInvocationID) 40
              42:      7(int)   Load 41
              43:     33(ptr)   AccessChain 30(ubo_in) 32 40
              44:      7(int)   Load 43
              45:     6(bool)   ULessThan 42 44
                                Branch 39
              39:             Label
              46:     6(bool) Phi 37 18 45 38
                              SelectionMerge 48 None
                              BranchConditional 46 47 48
              47:               Label
              51:     12(ptr)   AccessChain 10(gl_GlobalInvocationID) 11
              52:      7(int)   Load 51
              53:     33(ptr)   AccessChain 30(ubo_in) 32 19
              54:      7(int)   Load 53
              55:      7(int)   IMul 52 54
              56:     33(ptr)   AccessChain 30(ubo_in) 32 40
              57:      7(int)   Load 56
              58:      7(int)   IMul 55 57
              59:     12(ptr)   AccessChain 10(gl_GlobalInvocationID) 40
              60:      7(int)   Load 59
              61:     33(ptr)   AccessChain 30(ubo_in) 32 19
              62:      7(int)   Load 61
              63:      7(int)   IMul 60 62
              64:      7(int)   IAdd 58 63
              65:     12(ptr)   AccessChain 10(gl_GlobalInvocationID) 19
              66:      7(int)   Load 65
              67:      7(int)   IAdd 64 66
              68:     31(int)   Bitcast 67
                                Store 50(grid_idx) 68
              74:          71   Load 73(grid_light_counts)
              75:     31(int)   Load 50(grid_idx)
              77:   76(ivec4)   ImageRead 74 75
              78:      7(int)   CompositeExtract 77 0
                                Store 70(light_count) 78
              79:      7(int)   Load 70(light_count)
              80:     6(bool)   UGreaterThan 79 19
                                SelectionMerge 82 None
                                BranchConditional 80 81 82
              81:                 Label
              86:      7(int)     Load 70(light_count)
              88:     87(ptr)     ImageTexelPointer 84(grid_light_count_total) 85 19
              89:      7(int)     AtomicIAdd 88 40 19 86
                                  Store 83(offset) 89
              90:      7(int)     Load 83(offset)
              92:     6(bool)     ULessThan 90 91
                                  SelectionMerge 94 None
                                  BranchConditional 92 93 100
              93:                   Label
              96:          71       Load 95(grid_light_count_offsets)
              97:     31(int)       Load 50(grid_idx)
              98:      7(int)       Load 83(offset)
              99:   76(ivec4)       CompositeConstruct 98 19 19 19
                                    ImageWrite 96 97 99
                                    Branch 94
             100:                   Label
             104:         101       Load 103(grid_flags)
             105:     31(int)       Load 50(grid_idx)
                                    ImageWrite 104 105 106
                                    Branch 94
              94:                 Label
                                  Branch 82
              82:               Label
                                Branch 48
              48:             Label
                              Return
                              FunctionEnd
#endif

static const uint32_t calc_grid_offsets_comp[820] = {
    0x07230203, 0x00010000, 0x00080001, 0x0000006d,
    0x00000000, 0x00020011, 0x00000001, 0x00020011,
    0x0000002f, 0x00020011, 0x00000031, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0006000f, 0x00000005, 0x00000004, 0x6e69616d,
    0x00000000, 0x0000000a, 0x00060010, 0x00000004,
    0x00000011, 0x00000010, 0x00000010, 0x00000001,
    0x00030003, 0x00000002, 0x000001c2, 0x00040005,
    0x00000004, 0x6e69616d, 0x00000000, 0x00080005,
    0x0000000a, 0x475f6c67, 0x61626f6c, 0x766e496c,
    0x7461636f, 0x496e6f69, 0x00000044, 0x00030005,
    0x0000001c, 0x004f4255, 0x00050006, 0x0000001c,
    0x00000000, 0x77656976, 0x00000000, 0x00050006,
    0x0000001c, 0x00000001, 0x6d726f6e, 0x00006c61,
    0x00050006, 0x0000001c, 0x00000002, 0x65646f6d,
    0x0000006c, 0x00070006, 0x0000001c, 0x00000003,
    0x6a6f7270, 0x69746365, 0x635f6e6f, 0x0070696c,
    0x00060006, 0x0000001c, 0x00000004, 0x656c6974,
    0x7a69735f, 0x00000065, 0x00060006, 0x0000001c,
    0x00000005, 0x64697267, 0x6d69645f, 0x00000000,
    0x00050006, 0x0000001c, 0x00000006, 0x5f6d6163,
    0x00736f70, 0x00050006, 0x0000001c, 0x00000007,
    0x5f6d6163, 0x00726166, 0x00060006, 0x0000001c,
    0x00000008, 0x6f736572, 0x6974756c, 0x00006e6f,
    0x00060006, 0x0000001c, 0x00000009, 0x5f6d756e,
    0x6867696c, 0x00007374, 0x00040005, 0x0000001e,
    0x5f6f6275, 0x00006e69, 0x00050005, 0x00000032,
    0x64697267, 0x7864695f, 0x00000000, 0x00050005,
    0x00000046, 0x6867696c, 0x6f635f74, 0x00746e75,
    0x00070005, 0x00000049, 0x64697267, 0x67696c5f,
    0x635f7468, 0x746e756f, 0x00000073, 0x00040005,
    0x00000053, 0x7366666f, 0x00007465, 0x00080005,
    0x00000054, 0x64697267, 0x67696c5f, 0x635f7468,
    0x746e756f, 0x746f745f, 0x00006c61, 0x00090005,
    0x0000005f, 0x64697267, 0x67696c5f, 0x635f7468,
    0x746e756f, 0x66666f5f, 0x73746573, 0x00000000,
    0x00050005, 0x00000067, 0x64697267, 0x616c665f,
    0x00007367, 0x00040047, 0x0000000a, 0x0000000b,
    0x0000001c, 0x00040048, 0x0000001c, 0x00000000,
    0x00000005, 0x00050048, 0x0000001c, 0x00000000,
    0x00000023, 0x00000000, 0x00050048, 0x0000001c,
    0x00000000, 0x00000007, 0x00000010, 0x00040048,
    0x0000001c, 0x00000001, 0x00000005, 0x00050048,
    0x0000001c, 0x00000001, 0x00000023, 0x00000040,
    0x00050048, 0x0000001c, 0x00000001, 0x00000007,
    0x00000010, 0x00040048, 0x0000001c, 0x00000002,
    0x00000005, 0x00050048, 0x0000001c, 0x00000002,
    0x00000023, 0x00000080, 0x00050048, 0x0000001c,
    0x00000002, 0x00000007, 0x00000010, 0x00040048,
    0x0000001c, 0x00000003, 0x00000005, 0x00050048,
    0x0000001c, 0x00000003, 0x00000023, 0x000000c0,
    0x00050048, 0x0000001c, 0x00000003, 0x00000007,
    0x00000010, 0x00050048, 0x0000001c, 0x00000004,
    0x00000023, 0x00000100, 0x00050048, 0x0000001c,
    0x00000005, 0x00000023, 0x00000108, 0x00050048,
    0x0000001c, 0x00000006, 0x00000023, 0x00000110,
    0x00050048, 0x0000001c, 0x00000007, 0x00000023,
    0x0000011c, 0x00050048, 0x0000001c, 0x00000008,
    0x00000023, 0x00000120, 0x00050048, 0x0000001c,
    0x00000009, 0x00000023, 0x00000128, 0x00030047,
    0x0000001c, 0x00000002, 0x00040047, 0x0000001e,
    0x00000022, 0x00000000, 0x00040047, 0x0000001e,
    0x00000021, 0x00000000, 0x00040047, 0x00000049,
    0x00000022, 0x00000001, 0x00040047, 0x00000049,
    0x00000021, 0x00000002, 0x00040047, 0x00000054,
    0x00000022, 0x00000001, 0x00040047, 0x00000054,
    0x00000021, 0x00000003, 0x00040047, 0x0000005f,
    0x00000022, 0x00000001, 0x00040047, 0x0000005f,
    0x00000021, 0x00000004, 0x00040047, 0x00000067,
    0x00000022, 0x00000001, 0x00040047, 0x00000067,
    0x00000021, 0x00000000, 0x00040047, 0x0000006c,
    0x0000000b, 0x00000019, 0x00020013, 0x00000002,
    0x00030021, 0x00000003, 0x00000002, 0x00020014,
    0x00000006, 0x00040015, 0x00000007, 0x00000020,
    0x00000000, 0x00040017, 0x00000008, 0x00000007,
    0x00000003, 0x00040020, 0x00000009, 0x00000001,
    0x00000008, 0x0004003b, 0x00000009, 0x0000000a,
    0x00000001, 0x0004002b, 0x00000007, 0x0000000b,
    0x00000002, 0x00040020, 0x0000000c, 0x00000001,
    0x00000007, 0x0004002b, 0x00000007, 0x0000000f,
    0x00000100, 0x0004002b, 0x00000007, 0x00000013,
    0x00000000, 0x00030016, 0x00000016, 0x00000020,
    0x00040017, 0x00000017, 0x00000016, 0x00000004,
    0x00040018, 0x00000018, 0x00000017, 0x00000004,
    0x00040017, 0x00000019, 0x00000016, 0x00000002,
    0x00040017, 0x0000001a, 0x00000007, 0x00000002,
    0x00040017, 0x0000001b, 0x00000016, 0x00000003,
    0x000c001e, 0x0000001c, 0x00000018, 0x00000018,
    0x00000018, 0x00000018, 0x00000019, 0x0000001a,
    0x0000001b, 0x00000016, 0x00000019, 0x00000007,
    0x00040020, 0x0000001d, 0x00000002, 0x0000001c,
    0x0004003b, 0x0000001d, 0x0000001e, 0x00000002,
    0x00040015, 0x0000001f, 0x00000020, 0x00000001,
    0x0004002b, 0x0000001f, 0x00000020, 0x00000005,
    0x00040020, 0x00000021, 0x00000002, 0x00000007,
    0x0004002b, 0x00000007, 0x00000028, 0x00000001,
    0x00040020, 0x00000031, 0x00000007, 0x0000001f,
    0x00040020, 0x00000045, 0x00000007, 0x00000007,
    0x00090019, 0x00000047, 0x00000007, 0x00000005,
    0x00000000, 0x00000000, 0x00000000, 0x00000002,
    0x00000021, 0x00040020, 0x00000048, 0x00000000,
    0x00000047, 0x0004003b, 0x00000048, 0x00000049,
    0x00000000, 0x00040017, 0x0000004c, 0x00000007,
    0x00000004, 0x0004003b, 0x00000048, 0x00000054,
    0x00000000, 0x0004002b, 0x0000001f, 0x00000055,
    0x00000000, 0x00040020, 0x00000057, 0x0000000b,
    0x00000007, 0x0004002b, 0x00000007, 0x0000005b,
    0x00100000, 0x0004003b, 0x00000048, 0x0000005f,
    0x00000000, 0x00090019, 0x00000065, 0x00000007,
    0x00000005, 0x00000000, 0x00000000, 0x00000000,
    0x00000002, 0x00000027, 0x00040020, 0x00000066,
    0x00000000, 0x00000065, 0x0004003b, 0x00000066,
    0x00000067, 0x00000000, 0x0007002c, 0x0000004c,
    0x0000006a, 0x00000013, 0x00000013, 0x00000013,
    0x00000013, 0x0004002b, 0x00000007, 0x0000006b,
    0x00000010, 0x0006002c, 0x00000008, 0x0000006c,
    0x0000006b, 0x0000006b, 0x00000028, 0x00050036,
    0x00000002, 0x00000004, 0x00000000, 0x00000003,
    0x000200f8, 0x00000005, 0x0004003b, 0x00000031,
    0x00000032, 0x00000007, 0x0004003b, 0x00000045,
    0x00000046, 0x00000007, 0x0004003b, 0x00000045,
    0x00000053, 0x00000007, 0x00050041, 0x0000000c,
    0x0000000d, 0x0000000a, 0x0000000b, 0x0004003d,
    0x00000007, 0x0000000e, 0x0000000d, 0x000500b0,
    0x00000006, 0x00000010, 0x0000000e, 0x0000000f,
    0x000300f7, 0x00000012, 0x00000000, 0x000400fa,
    0x00000010, 0x00000011, 0x00000012, 0x000200f8,
    0x00000011, 0x00050041, 0x0000000c, 0x00000014,
    0x0000000a, 0x00000013, 0x0004003d, 0x00000007,
    0x00000015, 0x00000014, 0x00060041, 0x00000021,
    0x00000022, 0x0000001e, 0x00000020, 0x00000013,
    0x0004003d, 0x00000007, 0x00000023, 0x00000022,
    0x000500b0, 0x00000006, 0x00000024, 0x00000015,
    0x00000023, 0x000200f9, 0x00000012, 0x000200f8,
    0x00000012, 0x000700f5, 0x00000006, 0x00000025,
    0x00000010, 0x00000005, 0x00000024, 0x00000011,
    0x000300f7, 0x00000027, 0x00000000, 0x000400fa,
    0x00000025, 0x00000026, 0x00000027, 0x000200f8,
    0x00000026, 0x00050041, 0x0000000c, 0x00000029,
    0x0000000a, 0x00000028, 0x0004003d, 0x00000007,
    0x0000002a, 0x00000029, 0x00060041, 0x00000021,
    0x0000002b, 0x0000001e, 0x00000020, 0x00000028,
    0x0004003d, 0x00000007, 0x0000002c, 0x0000002b,
    0x000500b0, 0x00000006, 0x0000002d, 0x0000002a,
    0x0000002c, 0x000200f9, 0x00000027, 0x000200f8,
    0x00000027, 0x000700f5, 0x00000006, 0x0000002e,
    0x00000025, 0x00000012, 0x0000002d, 0x00000026,
    0x000300f7, 0x00000030, 0x00000000, 0x000400fa,
    0x0000002e, 0x0000002f, 0x00000030, 0x000200f8,
    0x0000002f, 0x00050041, 0x0000000c, 0x00000033,
    0x0000000a, 0x0000000b, 0x0004003d, 0x00000007,
    0x00000034, 0x00000033, 0x00060041, 0x00000021,
    0x00000035, 0x0000001e, 0x00000020, 0x00000013,
    0x0004003d, 0x00000007, 0x00000036, 0x00000035,
    0x00050084, 0x00000007, 0x00000037, 0x00000034,
    0x00000036, 0x00060041, 0x00000021, 0x00000038,
    0x0000001e, 0x00000020, 0x00000028, 0x0004003d,
    0x00000007, 0x00000039, 0x00000038, 0x00050084,
    0x00000007, 0x0000003a, 0x00000037, 0x00000039,
    0x00050041, 0x0000000c, 0x0000003b, 0x0000000a,
    0x00000028, 0x0004003d, 0x00000007, 0x0000003c,
    0x0000003b, 0x00060041, 0x00000021, 0x0000003d,
    0x0000001e, 0x00000020, 0x00000013, 0x0004003d,
    0x00000007, 0x0000003e, 0x0000003d, 0x00050084,
    0x00000007, 0x0000003f, 0x0000003c, 0x0000003e,
    0x00050080, 0x00000007, 0x00000040, 0x0000003a,
    0x0000003f, 0x00050041, 0x0000000c, 0x00000041,
    0x0000000a, 0x00000013, 0x0004003d, 0x00000007,
    0x00000042, 0x00000041, 0x00050080, 0x00000007,
    0x00000043, 0x00000040, 0x00000042, 0x0004007c,
    0x0000001f, 0x00000044, 0x00000043, 0x0003003e,
    0x00000032, 0x00000044, 0x0004003d, 0x00000047,
    0x0000004a, 0x00000049, 0x0004003d, 0x0000001f,
    0x0000004b, 0x00000032, 0x00050062, 0x0000004c,
    0x0000004d, 0x0000004a, 0x0000004b, 0x00050051,
    0x00000007, 0x0000004e, 0x0000004d, 0x00000000,
    0x0003003e, 0x00000046, 0x0000004e, 0x0004003d,
    0x00000007, 0x0000004f, 0x00000046, 0x000500ac,
    0x00000006, 0x00000050, 0x0000004f, 0x00000013,
    0x000300f7, 0x00000052, 0x00000000, 0x000400fa,
    0x00000050, 0x00000051, 0x00000052, 0x000200f8,
    0x00000051, 0x0004003d, 0x00000007, 0x00000056,
    0x00000046, 0x0006003c, 0x00000057, 0x00000058,
    0x00000054, 0x00000055, 0x00000013, 0x000700ea,
    0x00000007, 0x00000059, 0x00000058, 0x00000028,
    0x00000013, 0x00000056, 0x0003003e, 0x00000053,
    0x00000059, 0x0004003d, 0x00000007, 0x0000005a,
    0x00000053, 0x000500b0, 0x00000006, 0x0000005c,
    0x0000005a, 0x0000005b, 0x000300f7, 0x0000005e,
    0x00000000, 0x000400fa, 0x0000005c, 0x0000005d,
    0x00000064, 0x000200f8, 0x0000005d, 0x0004003d,
    0x00000047, 0x00000060, 0x0000005f, 0x0004003d,
    0x0000001f, 0x00000061, 0x00000032, 0x0004003d,
    0x00000007, 0x00000062, 0x00000053, 0x00070050,
    0x0000004c, 0x00000063, 0x00000062, 0x00000013,
    0x00000013, 0x00000013, 0x00040063, 0x00000060,
    0x00000061, 0x00000063, 0x000200f9, 0x0000005e,
    0x000200f8, 0x00000064, 0x0004003d, 0x00000065,
    0x00000068, 0x00000067, 0x0004003d, 0x0000001f,
    0x00000069, 0x00000032, 0x00040063, 0x00000068,
    0x00000069, 0x0000006a, 0x000200f9, 0x0000005e,
    0x000200f8, 0x0000005e, 0x000200f9, 0x00000052,
    0x000200f8, 0x00000052, 0x000200f9, 0x00000030,
    0x000200f8, 0x00000030, 0x000100fd, 0x00010038,
};
