#include <stdint.h>

#if 0
C:/msys64/home/sydlu/CProjects/clustered-forward-demo-vk/demo/calc_light_grids.comp
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 539

                              Capability Shader
                              Capability ImageBuffer
                              Capability StorageImageExtendedFormats
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint GLCompute 4  "main" 157
                              ExecutionMode 4 LocalSize 32 1 1
                              Source GLSL 450
                              Name 4  "main"
                              Name 11  "get_view_space_pos(vf3;"
                              Name 10  "pos_in"
                              Name 16  "view_pos_to_frag_pos(vf3;"
                              Name 15  "view_pos"
                              Name 23  "view_pos_to_grid_coord(vf2;f1;"
                              Name 21  "frag_pos"
                              Name 22  "view_z"
                              Name 32  "grid_coord_to_grid_idx(u1;u1;u1;"
                              Name 29  "i"
                              Name 30  "j"
                              Name 31  "k"
                              Name 37  "mark_skip_light(u1;vf3;"
                              Name 35  "light_idx"
                              Name 36  "light_pos"
                              Name 42  "UBO"
                              MemberName 42(UBO) 0  "view"
                              MemberName 42(UBO) 1  "normal"
                              MemberName 42(UBO) 2  "model"
                              MemberName 42(UBO) 3  "projection_clip"
                              MemberName 42(UBO) 4  "tile_size"
                              MemberName 42(UBO) 5  "grid_dim"
                              MemberName 42(UBO) 6  "cam_pos"
                              MemberName 42(UBO) 7  "cam_far"
                              MemberName 42(UBO) 8  "resolution"
                              MemberName 42(UBO) 9  "num_lights"
                              Name 44  "ubo_in"
                              Name 60  "clip_pos"
                              Name 70  "ndc"
                              Name 91  "c"
                              Name 145  "light_pos_ranges"
                              Name 154  "light_idx"
                              Name 157  "gl_GlobalInvocationID"
                              Name 169  "pos_range_in"
                              Name 174  "vp"
                              Name 175  "param"
                              Name 179  "vp_min"
                              Name 186  "vp_max"
                              Name 225  "param"
                              Name 227  "param"
                              Name 243  "fp_a"
                              Name 251  "param"
                              Name 253  "fp_b"
                              Name 261  "param"
                              Name 263  "fp_c"
                              Name 271  "param"
                              Name 273  "fp_d"
                              Name 281  "param"
                              Name 283  "fp_min"
                              Name 287  "fp_max"
                              Name 292  "exit"
                              Name 378  "param"
                              Name 380  "param"
                              Name 394  "grid_coord_min"
                              Name 395  "param"
                              Name 397  "param"
                              Name 401  "grid_coord_max"
                              Name 402  "param"
                              Name 404  "param"
                              Name 409  "bound_min"
                              Name 412  "bound_max"
                              Name 417  "light_bounds"
                              Name 470  "i"
                              Name 482  "j"
                              Name 494  "k"
                              Name 507  "grid_idx"
                              Name 508  "param"
                              Name 510  "param"
                              Name 512  "param"
                              Name 517  "grid_flags"
                              Name 525  "grid_light_counts"
                              MemberDecorate 42(UBO) 0 ColMajor
                              MemberDecorate 42(UBO) 0 Offset 0
                              MemberDecorate 42(UBO) 0 MatrixStride 16
                              MemberDecorate 42(UBO) 1 ColMajor
                              MemberDecorate 42(UBO) 1 Offset 64
                              MemberDecorate 42(UBO) 1 MatrixStride 16
                              MemberDecorate 42(UBO) 2 ColMajor
                              MemberDecorate 42(UBO) 2 Offset 128
                              MemberDecorate 42(UBO) 2 MatrixStride 16
                              MemberDecorate 42(UBO) 3 ColMajor
                              MemberDecorate 42(UBO) 3 Offset 192
                              MemberDecorate 42(UBO) 3 MatrixStride 16
                              MemberDecorate 42(UBO) 4 Offset 256
                              MemberDecorate 42(UBO) 5 Offset 264
                              MemberDecorate 42(UBO) 6 Offset 272
                              MemberDecorate 42(UBO) 7 Offset 284
                              MemberDecorate 42(UBO) 8 Offset 288
                              MemberDecorate 42(UBO) 9 Offset 296
                              Decorate 42(UBO) Block
                              Decorate 44(ubo_in) DescriptorSet 0
                              Decorate 44(ubo_in) Binding 0
                              Decorate 145(light_pos_ranges) DescriptorSet 0
                              Decorate 145(light_pos_ranges) Binding 1
                              Decorate 157(gl_GlobalInvocationID) BuiltIn GlobalInvocationId
                              Decorate 417(light_bounds) DescriptorSet 1
                              Decorate 417(light_bounds) Binding 1
                              Decorate 517(grid_flags) DescriptorSet 1
                              Decorate 517(grid_flags) Binding 0
                              Decorate 525(grid_light_counts) DescriptorSet 1
                              Decorate 525(grid_light_counts) Binding 2
                              Decorate 538 BuiltIn WorkgroupSize
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 3
               8:             TypePointer Function 7(fvec3)
               9:             TypeFunction 7(fvec3) 8(ptr)
              13:             TypeVector 6(float) 2
              14:             TypeFunction 13(fvec2) 8(ptr)
              18:             TypePointer Function 13(fvec2)
              19:             TypePointer Function 6(float)
              20:             TypeFunction 7(fvec3) 18(ptr) 19(ptr)
              25:             TypeInt 32 0
              26:             TypePointer Function 25(int)
              27:             TypeInt 32 1
              28:             TypeFunction 27(int) 26(ptr) 26(ptr) 26(ptr)
              34:             TypeFunction 2 26(ptr) 8(ptr)
              39:             TypeVector 6(float) 4
              40:             TypeMatrix 39(fvec4) 4
              41:             TypeVector 25(int) 2
         42(UBO):             TypeStruct 40 40 40 40 13(fvec2) 41(ivec2) 7(fvec3) 6(float) 13(fvec2) 25(int)
              43:             TypePointer Uniform 42(UBO)
      44(ubo_in):     43(ptr) Variable Uniform
              45:     27(int) Constant 0
              46:             TypePointer Uniform 40
              50:    6(float) Constant 1065353216
              59:             TypePointer Function 39(fvec4)
              61:     27(int) Constant 3
              73:     25(int) Constant 3
              78:    6(float) Constant 1056964608
              84:     27(int) Constant 8
              85:             TypePointer Uniform 13(fvec2)
              93:     27(int) Constant 4
              99:    6(float) Constant 1132396544
             100:    6(float) Constant 0
             101:    6(float) Constant 1132462080
             104:    6(float) Constant 1036831949
             106:     27(int) Constant 7
             107:             TypePointer Uniform 6(float)
             117:     25(int) Constant 2
             122:     27(int) Constant 5
             123:     25(int) Constant 0
             124:             TypePointer Uniform 25(int)
             127:     25(int) Constant 1
             143:             TypeImage 6(float) Buffer nonsampled format:Rgba32f
             144:             TypePointer UniformConstant 143
145(light_pos_ranges):    144(ptr) Variable UniformConstant
             155:             TypeVector 25(int) 3
             156:             TypePointer Input 155(ivec3)
157(gl_GlobalInvocationID):    156(ptr) Variable Input
             158:             TypePointer Input 25(int)
             162:     27(int) Constant 9
             165:             TypeBool
             211:    6(float) Constant 3184315597
             291:             TypePointer Function 165(bool)
             293:   165(bool) ConstantFalse
             385:   13(fvec2) ConstantComposite 100 100
             408:             TypePointer Function 155(ivec3)
             415:             TypeImage 25(int) Buffer nonsampled format:R32ui
             416:             TypePointer UniformConstant 415
417(light_bounds):    416(ptr) Variable UniformConstant
             420:     25(int) Constant 6
             426:             TypeVector 25(int) 4
             455:     25(int) Constant 4
             464:     25(int) Constant 5
             506:             TypePointer Function 27(int)
             515:             TypeImage 25(int) Buffer nonsampled format:R8ui
             516:             TypePointer UniformConstant 515
 517(grid_flags):    516(ptr) Variable UniformConstant
525(grid_light_counts):    416(ptr) Variable UniformConstant
             527:             TypePointer Image 25(int)
             531:     27(int) Constant 1
             537:     25(int) Constant 32
             538:  155(ivec3) ConstantComposite 537 127 127
         4(main):           2 Function None 3
               5:             Label
  154(light_idx):     26(ptr) Variable Function
169(pos_range_in):     59(ptr) Variable Function
         174(vp):      8(ptr) Variable Function
      175(param):      8(ptr) Variable Function
     179(vp_min):      8(ptr) Variable Function
     186(vp_max):      8(ptr) Variable Function
      225(param):     26(ptr) Variable Function
      227(param):      8(ptr) Variable Function
       243(fp_a):     18(ptr) Variable Function
      251(param):      8(ptr) Variable Function
       253(fp_b):     18(ptr) Variable Function
      261(param):      8(ptr) Variable Function
       263(fp_c):     18(ptr) Variable Function
      271(param):      8(ptr) Variable Function
       273(fp_d):     18(ptr) Variable Function
      281(param):      8(ptr) Variable Function
     283(fp_min):     18(ptr) Variable Function
     287(fp_max):     18(ptr) Variable Function
       292(exit):    291(ptr) Variable Function
      378(param):     26(ptr) Variable Function
      380(param):      8(ptr) Variable Function
394(grid_coord_min):      8(ptr) Variable Function
      395(param):     18(ptr) Variable Function
      397(param):     19(ptr) Variable Function
401(grid_coord_max):      8(ptr) Variable Function
      402(param):     18(ptr) Variable Function
      404(param):     19(ptr) Variable Function
  409(bound_min):    408(ptr) Variable Function
  412(bound_max):    408(ptr) Variable Function
          470(i):     26(ptr) Variable Function
          482(j):     26(ptr) Variable Function
          494(k):     26(ptr) Variable Function
   507(grid_idx):    506(ptr) Variable Function
      508(param):     26(ptr) Variable Function
      510(param):     26(ptr) Variable Function
      512(param):     26(ptr) Variable Function
             159:    158(ptr) AccessChain 157(gl_GlobalInvocationID) 123
             160:     25(int) Load 159
                              Store 154(light_idx) 160
             161:     25(int) Load 154(light_idx)
             163:    124(ptr) AccessChain 44(ubo_in) 162
             164:     25(int) Load 163
             166:   165(bool) ULessThan 161 164
                              SelectionMerge 168 None
                              BranchConditional 166 167 168
             167:               Label
             170:         143   Load 145(light_pos_ranges)
             171:     25(int)   Load 154(light_idx)
             172:     27(int)   Bitcast 171
             173:   39(fvec4)   ImageRead 170 172
                                Store 169(pos_range_in) 173
             176:   39(fvec4)   Load 169(pos_range_in)
             177:    7(fvec3)   VectorShuffle 176 176 0 1 2
                                Store 175(param) 177
             178:    7(fvec3)   FunctionCall 11(get_view_space_pos(vf3;) 175(param)
                                Store 174(vp) 178
             180:     19(ptr)   AccessChain 174(vp) 123
             181:    6(float)   Load 180
             182:     19(ptr)   AccessChain 169(pos_range_in) 73
             183:    6(float)   Load 182
             184:    6(float)   FSub 181 183
             185:     19(ptr)   AccessChain 179(vp_min) 123
                                Store 185 184
             187:     19(ptr)   AccessChain 174(vp) 123
             188:    6(float)   Load 187
             189:     19(ptr)   AccessChain 169(pos_range_in) 73
             190:    6(float)   Load 189
             191:    6(float)   FAdd 188 190
             192:     19(ptr)   AccessChain 186(vp_max) 123
                                Store 192 191
             193:    7(fvec3)   Load 174(vp)
             194:   13(fvec2)   VectorShuffle 193 193 1 2
             195:     19(ptr)   AccessChain 169(pos_range_in) 73
             196:    6(float)   Load 195
             197:   13(fvec2)   CompositeConstruct 196 196
             198:   13(fvec2)   FAdd 194 197
             199:    7(fvec3)   Load 179(vp_min)
             200:    7(fvec3)   VectorShuffle 199 198 0 3 4
                                Store 179(vp_min) 200
             201:    7(fvec3)   Load 174(vp)
             202:   13(fvec2)   VectorShuffle 201 201 1 2
             203:     19(ptr)   AccessChain 169(pos_range_in) 73
             204:    6(float)   Load 203
             205:   13(fvec2)   CompositeConstruct 204 204
             206:   13(fvec2)   FSub 202 205
             207:    7(fvec3)   Load 186(vp_max)
             208:    7(fvec3)   VectorShuffle 207 206 0 3 4
                                Store 186(vp_max) 208
             209:     19(ptr)   AccessChain 186(vp_max) 117
             210:    6(float)   Load 209
             212:   165(bool)   FOrdGreaterThanEqual 210 211
             213:   165(bool)   LogicalNot 212
                                SelectionMerge 215 None
                                BranchConditional 213 214 215
             214:                 Label
             216:     19(ptr)     AccessChain 179(vp_min) 117
             217:    6(float)     Load 216
             218:    107(ptr)     AccessChain 44(ubo_in) 106
             219:    6(float)     Load 218
             220:    6(float)     FNegate 219
             221:   165(bool)     FOrdLessThanEqual 217 220
                                  Branch 215
             215:               Label
             222:   165(bool)   Phi 212 167 221 214
                                SelectionMerge 224 None
                                BranchConditional 222 223 224
             223:                 Label
             226:     25(int)     Load 154(light_idx)
                                  Store 225(param) 226
             228:   39(fvec4)     Load 169(pos_range_in)
             229:    7(fvec3)     VectorShuffle 228 228 0 1 2
                                  Store 227(param) 229
             230:           2     FunctionCall 37(mark_skip_light(u1;vf3;) 225(param) 227(param)
                                  Return
             224:               Label
             232:     19(ptr)   AccessChain 179(vp_min) 117
             233:    6(float)   Load 232
             234:    6(float)   ExtInst 1(GLSL.std.450) 37(FMin) 211 233
             235:     19(ptr)   AccessChain 179(vp_min) 117
                                Store 235 234
             236:    107(ptr)   AccessChain 44(ubo_in) 106
             237:    6(float)   Load 236
             238:    6(float)   FNegate 237
             239:     19(ptr)   AccessChain 186(vp_max) 117
             240:    6(float)   Load 239
             241:    6(float)   ExtInst 1(GLSL.std.450) 40(FMax) 238 240
             242:     19(ptr)   AccessChain 186(vp_max) 117
                                Store 242 241
             244:    7(fvec3)   Load 179(vp_min)
             245:   13(fvec2)   VectorShuffle 244 244 0 1
             246:     19(ptr)   AccessChain 179(vp_min) 117
             247:    6(float)   Load 246
             248:    6(float)   CompositeExtract 245 0
             249:    6(float)   CompositeExtract 245 1
             250:    7(fvec3)   CompositeConstruct 248 249 247
                                Store 251(param) 250
             252:   13(fvec2)   FunctionCall 16(view_pos_to_frag_pos(vf3;) 251(param)
                                Store 243(fp_a) 252
             254:    7(fvec3)   Load 179(vp_min)
             255:   13(fvec2)   VectorShuffle 254 254 0 1
             256:     19(ptr)   AccessChain 186(vp_max) 117
             257:    6(float)   Load 256
             258:    6(float)   CompositeExtract 255 0
             259:    6(float)   CompositeExtract 255 1
             260:    7(fvec3)   CompositeConstruct 258 259 257
                                Store 261(param) 260
             262:   13(fvec2)   FunctionCall 16(view_pos_to_frag_pos(vf3;) 261(param)
                                Store 253(fp_b) 262
             264:    7(fvec3)   Load 186(vp_max)
             265:   13(fvec2)   VectorShuffle 264 264 0 1
             266:     19(ptr)   AccessChain 186(vp_max) 117
             267:    6(float)   Load 266
             268:    6(float)   CompositeExtract 265 0
             269:    6(float)   CompositeExtract 265 1
             270:    7(fvec3)   CompositeConstruct 268 269 267
                                Store 271(param) 270
             272:   13(fvec2)   FunctionCall 16(view_pos_to_frag_pos(vf3;) 271(param)
                                Store 263(fp_c) 272
             274:    7(fvec3)   Load 186(vp_max)
             275:   13(fvec2)   VectorShuffle 274 274 0 1
             276:     19(ptr)   AccessChain 179(vp_min) 117
             277:    6(float)   Load 276
             278:    6(float)   CompositeExtract 275 0
             279:    6(float)   CompositeExtract 275 1
             280:    7(fvec3)   CompositeConstruct 278 279 277
                                Store 281(param) 280
             282:   13(fvec2)   FunctionCall 16(view_pos_to_frag_pos(vf3;) 281(param)
                                Store 273(fp_d) 282
             284:   13(fvec2)   Load 243(fp_a)
             285:   13(fvec2)   Load 253(fp_b)
             286:   13(fvec2)   ExtInst 1(GLSL.std.450) 37(FMin) 284 285
                                Store 283(fp_min) 286
             288:   13(fvec2)   Load 263(fp_c)
             289:   13(fvec2)   Load 273(fp_d)
             290:   13(fvec2)   ExtInst 1(GLSL.std.450) 40(FMax) 288 289
                                Store 287(fp_max) 290
                                Store 292(exit) 293
             294:   165(bool)   Load 292(exit)
             295:   165(bool)   LogicalNot 294
                                SelectionMerge 297 None
                                BranchConditional 295 296 297
             296:                 Label
             298:     19(ptr)     AccessChain 283(fp_min) 123
             299:    6(float)     Load 298
             300:   165(bool)     FOrdLessThan 299 100
                                  SelectionMerge 302 None
                                  BranchConditional 300 301 302
             301:                   Label
             303:     19(ptr)       AccessChain 287(fp_max) 123
             304:    6(float)       Load 303
             305:   165(bool)       FOrdLessThan 304 100
                                    Branch 302
             302:                 Label
             306:   165(bool)     Phi 300 296 305 301
                                  Branch 297
             297:               Label
             307:   165(bool)   Phi 294 224 306 302
             308:   165(bool)   LogicalNot 307
                                SelectionMerge 310 None
                                BranchConditional 308 309 310
             309:                 Label
             311:     19(ptr)     AccessChain 283(fp_min) 127
             312:    6(float)     Load 311
             313:   165(bool)     FOrdLessThan 312 100
                                  SelectionMerge 315 None
                                  BranchConditional 313 314 315
             314:                   Label
             316:     19(ptr)       AccessChain 287(fp_max) 127
             317:    6(float)       Load 316
             318:   165(bool)       FOrdLessThan 317 100
                                    Branch 315
             315:                 Label
             319:   165(bool)     Phi 313 309 318 314
                                  Branch 310
             310:               Label
             320:   165(bool)   Phi 307 297 319 315
                                Store 292(exit) 320
             321:   165(bool)   Load 292(exit)
             322:   165(bool)   LogicalNot 321
                                SelectionMerge 324 None
                                BranchConditional 322 323 324
             323:                 Label
             325:     19(ptr)     AccessChain 283(fp_min) 123
             326:    6(float)     Load 325
             327:    107(ptr)     AccessChain 44(ubo_in) 84 123
             328:    6(float)     Load 327
             329:   165(bool)     FOrdGreaterThanEqual 326 328
                                  SelectionMerge 331 None
                                  BranchConditional 329 330 331
             330:                   Label
             332:     19(ptr)       AccessChain 287(fp_max) 123
             333:    6(float)       Load 332
             334:    107(ptr)       AccessChain 44(ubo_in) 84 123
             335:    6(float)       Load 334
             336:   165(bool)       FOrdGreaterThanEqual 333 335
                                    Branch 331
             331:                 Label
             337:   165(bool)     Phi 329 323 336 330
                                  Branch 324
             324:               Label
             338:   165(bool)   Phi 321 310 337 331
             339:   165(bool)   LogicalNot 338
                                SelectionMerge 341 None
                                BranchConditional 339 340 341
             340:                 Label
             342:     19(ptr)     AccessChain 283(fp_min) 127
             343:    6(float)     Load 342
             344:    107(ptr)     AccessChain 44(ubo_in) 84 127
             345:    6(float)     Load 344
             346:   165(bool)     FOrdGreaterThanEqual 343 345
                                  SelectionMerge 348 None
                                  BranchConditional 346 347 348
             347:                   Label
             349:     19(ptr)       AccessChain 287(fp_max) 127
             350:    6(float)       Load 349
             351:    107(ptr)       AccessChain 44(ubo_in) 84 127
             352:    6(float)       Load 351
             353:   165(bool)       FOrdGreaterThanEqual 350 352
                                    Branch 348
             348:                 Label
             354:   165(bool)     Phi 346 340 353 347
                                  Branch 341
             341:               Label
             355:   165(bool)   Phi 338 324 354 348
                                Store 292(exit) 355
             356:   165(bool)   Load 292(exit)
             357:   165(bool)   LogicalNot 356
                                SelectionMerge 359 None
                                BranchConditional 357 358 359
             358:                 Label
             360:     19(ptr)     AccessChain 283(fp_min) 123
             361:    6(float)     Load 360
             362:     19(ptr)     AccessChain 287(fp_max) 123
             363:    6(float)     Load 362
             364:   165(bool)     FOrdGreaterThan 361 363
                                  Branch 359
             359:               Label
             365:   165(bool)   Phi 356 341 364 358
             366:   165(bool)   LogicalNot 365
                                SelectionMerge 368 None
                                BranchConditional 366 367 368
             367:                 Label
             369:     19(ptr)     AccessChain 283(fp_min) 127
             370:    6(float)     Load 369
             371:     19(ptr)     AccessChain 287(fp_max) 127
             372:    6(float)     Load 371
             373:   165(bool)     FOrdGreaterThan 370 372
                                  Branch 368
             368:               Label
             374:   165(bool)   Phi 365 359 373 367
                                Store 292(exit) 374
             375:   165(bool)   Load 292(exit)
                                SelectionMerge 377 None
                                BranchConditional 375 376 377
             376:                 Label
             379:     25(int)     Load 154(light_idx)
                                  Store 378(param) 379
             381:   39(fvec4)     Load 169(pos_range_in)
             382:    7(fvec3)     VectorShuffle 381 381 0 1 2
                                  Store 380(param) 382
             383:           2     FunctionCall 37(mark_skip_light(u1;vf3;) 378(param) 380(param)
                                  Return
             377:               Label
             386:   13(fvec2)   Load 283(fp_min)
             387:   13(fvec2)   ExtInst 1(GLSL.std.450) 40(FMax) 385 386
                                Store 283(fp_min) 387
             388:     85(ptr)   AccessChain 44(ubo_in) 84
             389:   13(fvec2)   Load 388
             390:   13(fvec2)   CompositeConstruct 50 50
             391:   13(fvec2)   FSub 389 390
             392:   13(fvec2)   Load 287(fp_max)
             393:   13(fvec2)   ExtInst 1(GLSL.std.450) 37(FMin) 391 392
                                Store 287(fp_max) 393
             396:   13(fvec2)   Load 283(fp_min)
                                Store 395(param) 396
             398:     19(ptr)   AccessChain 179(vp_min) 117
             399:    6(float)   Load 398
                                Store 397(param) 399
             400:    7(fvec3)   FunctionCall 23(view_pos_to_grid_coord(vf2;f1;) 395(param) 397(param)
                                Store 394(grid_coord_min) 400
             403:   13(fvec2)   Load 287(fp_max)
                                Store 402(param) 403
             405:     19(ptr)   AccessChain 186(vp_max) 117
             406:    6(float)   Load 405
                                Store 404(param) 406
             407:    7(fvec3)   FunctionCall 23(view_pos_to_grid_coord(vf2;f1;) 402(param) 404(param)
                                Store 401(grid_coord_max) 407
             410:    7(fvec3)   Load 394(grid_coord_min)
             411:  155(ivec3)   ConvertFToU 410
                                Store 409(bound_min) 411
             413:    7(fvec3)   Load 401(grid_coord_max)
             414:  155(ivec3)   ConvertFToU 413
                                Store 412(bound_max) 414
             418:         415   Load 417(light_bounds)
             419:     25(int)   Load 154(light_idx)
             421:     25(int)   IMul 419 420
             422:     25(int)   IAdd 421 123
             423:     27(int)   Bitcast 422
             424:     26(ptr)   AccessChain 409(bound_min) 123
             425:     25(int)   Load 424
             427:  426(ivec4)   CompositeConstruct 425 123 123 123
                                ImageWrite 418 423 427
             428:         415   Load 417(light_bounds)
             429:     25(int)   Load 154(light_idx)
             430:     25(int)   IMul 429 420
             431:     25(int)   IAdd 430 127
             432:     27(int)   Bitcast 431
             433:     26(ptr)   AccessChain 409(bound_min) 127
             434:     25(int)   Load 433
             435:  426(ivec4)   CompositeConstruct 434 123 123 123
                                ImageWrite 428 432 435
             436:         415   Load 417(light_bounds)
             437:     25(int)   Load 154(light_idx)
             438:     25(int)   IMul 437 420
             439:     25(int)   IAdd 438 117
             440:     27(int)   Bitcast 439
             441:     26(ptr)   AccessChain 409(bound_min) 117
             442:     25(int)   Load 441
             443:  426(ivec4)   CompositeConstruct 442 123 123 123
                                ImageWrite 436 440 443
             444:         415   Load 417(light_bounds)
             445:     25(int)   Load 154(light_idx)
             446:     25(int)   IMul 445 420
             447:     25(int)   IAdd 446 73
             448:     27(int)   Bitcast 447
             449:     26(ptr)   AccessChain 412(bound_max) 123
             450:     25(int)   Load 449
             451:  426(ivec4)   CompositeConstruct 450 123 123 123
                                ImageWrite 444 448 451
             452:         415   Load 417(light_bounds)
             453:     25(int)   Load 154(light_idx)
             454:     25(int)   IMul 453 420
             456:     25(int)   IAdd 454 455
             457:     27(int)   Bitcast 456
             458:     26(ptr)   AccessChain 412(bound_max) 127
             459:     25(int)   Load 458
             460:  426(ivec4)   CompositeConstruct 459 123 123 123
                                ImageWrite 452 457 460
             461:         415   Load 417(light_bounds)
             462:     25(int)   Load 154(light_idx)
             463:     25(int)   IMul 462 420
             465:     25(int)   IAdd 463 464
             466:     27(int)   Bitcast 465
             467:     26(ptr)   AccessChain 412(bound_max) 117
             468:     25(int)   Load 467
             469:  426(ivec4)   CompositeConstruct 468 123 123 123
                                ImageWrite 461 466 469
             471:     26(ptr)   AccessChain 409(bound_min) 123
             472:     25(int)   Load 471
                                Store 470(i) 472
                                Branch 473
             473:               Label
                                LoopMerge 475 476 None
                                Branch 477
             477:               Label
             478:     25(int)   Load 470(i)
             479:     26(ptr)   AccessChain 412(bound_max) 123
             480:     25(int)   Load 479
             481:   165(bool)   ULessThanEqual 478 480
                                BranchConditional 481 474 475
             474:                 Label
             483:     26(ptr)     AccessChain 409(bound_min) 127
             484:     25(int)     Load 483
                                  Store 482(j) 484
                                  Branch 485
             485:                 Label
                                  LoopMerge 487 488 None
                                  Branch 489
             489:                 Label
             490:     25(int)     Load 482(j)
             491:     26(ptr)     AccessChain 412(bound_max) 127
             492:     25(int)     Load 491
             493:   165(bool)     ULessThanEqual 490 492
                                  BranchConditional 493 486 487
             486:                   Label
             495:     26(ptr)       AccessChain 409(bound_min) 117
             496:     25(int)       Load 495
                                    Store 494(k) 496
                                    Branch 497
             497:                   Label
                                    LoopMerge 499 500 None
                                    Branch 501
             501:                   Label
             502:     25(int)       Load 494(k)
             503:     26(ptr)       AccessChain 412(bound_max) 117
             504:     25(int)       Load 503
             505:   165(bool)       ULessThanEqual 502 504
                                    BranchConditional 505 498 499
             498:                     Label
             509:     25(int)         Load 470(i)
                                      Store 508(param) 509
             511:     25(int)         Load 482(j)
                                      Store 510(param) 511
             513:     25(int)         Load 494(k)
                                      Store 512(param) 513
             514:     27(int)         FunctionCall 32(grid_coord_to_grid_idx(u1;u1;u1;) 508(param) 510(param) 512(param)
                                      Store 507(grid_idx) 514
             518:         515         Load 517(grid_flags)
             519:     27(int)         Load 507(grid_idx)
             520:  426(ivec4)         ImageRead 518 519
             521:     25(int)         CompositeExtract 520 0
             522:   165(bool)         IEqual 521 127
                                      SelectionMerge 524 None
                                      BranchConditional 522 523 524
             523:                       Label
             526:     27(int)           Load 507(grid_idx)
             528:    527(ptr)           ImageTexelPointer 525(grid_light_counts) 526 123
             529:     25(int)           AtomicIAdd 528 127 123 127
                                        Branch 524
             524:                     Label
                                      Branch 500
             500:                     Label
             530:     25(int)         Load 494(k)
             532:     25(int)         IAdd 530 531
                                      Store 494(k) 532
                                      Branch 497
             499:                   Label
                                    Branch 488
             488:                   Label
             533:     25(int)       Load 482(j)
             534:     25(int)       IAdd 533 531
                                    Store 482(j) 534
                                    Branch 485
             487:                 Label
                                  Branch 476
             476:                 Label
             535:     25(int)     Load 470(i)
             536:     25(int)     IAdd 535 531
                                  Store 470(i) 536
                                  Branch 473
             475:               Label
                                Branch 168
             168:             Label
                              Return
                              FunctionEnd
11(get_view_space_pos(vf3;):    7(fvec3) Function None 9
      10(pos_in):      8(ptr) FunctionParameter
              12:             Label
              47:     46(ptr) AccessChain 44(ubo_in) 45
              48:          40 Load 47
              49:    7(fvec3) Load 10(pos_in)
              51:    6(float) CompositeExtract 49 0
              52:    6(float) CompositeExtract 49 1
              53:    6(float) CompositeExtract 49 2
              54:   39(fvec4) CompositeConstruct 51 52 53 50
              55:   39(fvec4) MatrixTimesVector 48 54
              56:    7(fvec3) VectorShuffle 55 55 0 1 2
                              ReturnValue 56
                              FunctionEnd
16(view_pos_to_frag_pos(vf3;):   13(fvec2) Function None 14
    15(view_pos):      8(ptr) FunctionParameter
              17:             Label
    60(clip_pos):     59(ptr) Variable Function
         70(ndc):      8(ptr) Variable Function
              62:     46(ptr) AccessChain 44(ubo_in) 61
              63:          40 Load 62
              64:    7(fvec3) Load 15(view_pos)
              65:    6(float) CompositeExtract 64 0
              66:    6(float) CompositeExtract 64 1
              67:    6(float) CompositeExtract 64 2
              68:   39(fvec4) CompositeConstruct 65 66 67 50
              69:   39(fvec4) MatrixTimesVector 63 68
                              Store 60(clip_pos) 69
              71:   39(fvec4) Load 60(clip_pos)
              72:    7(fvec3) VectorShuffle 71 71 0 1 2
              74:     19(ptr) AccessChain 60(clip_pos) 73
              75:    6(float) Load 74
              76:    7(fvec3) CompositeConstruct 75 75 75
              77:    7(fvec3) FDiv 72 76
                              Store 70(ndc) 77
              79:    7(fvec3) Load 70(ndc)
              80:   13(fvec2) VectorShuffle 79 79 0 1
              81:   13(fvec2) CompositeConstruct 50 50
              82:   13(fvec2) FAdd 81 80
              83:   13(fvec2) VectorTimesScalar 82 78
              86:     85(ptr) AccessChain 44(ubo_in) 84
              87:   13(fvec2) Load 86
              88:   13(fvec2) FMul 83 87
                              ReturnValue 88
                              FunctionEnd
23(view_pos_to_grid_coord(vf2;f1;):    7(fvec3) Function None 20
    21(frag_pos):     18(ptr) FunctionParameter
      22(view_z):     19(ptr) FunctionParameter
              24:             Label
           91(c):      8(ptr) Variable Function
              92:   13(fvec2) Load 21(frag_pos)
              94:     85(ptr) AccessChain 44(ubo_in) 93
              95:   13(fvec2) Load 94
              96:   13(fvec2) FDiv 92 95
              97:    7(fvec3) Load 91(c)
              98:    7(fvec3) VectorShuffle 97 96 3 4 2
                              Store 91(c) 98
             102:    6(float) Load 22(view_z)
             103:    6(float) FNegate 102
             105:    6(float) FSub 103 104
             108:    107(ptr) AccessChain 44(ubo_in) 106
             109:    6(float) Load 108
             110:    6(float) FSub 109 104
             111:    6(float) FDiv 105 110
             112:    6(float) FAdd 111 50
             113:    6(float) ExtInst 1(GLSL.std.450) 28(Log) 112
             114:    6(float) FMul 101 113
             115:    6(float) ExtInst 1(GLSL.std.450) 40(FMax) 100 114
             116:    6(float) ExtInst 1(GLSL.std.450) 37(FMin) 99 115
             118:     19(ptr) AccessChain 91(c) 117
                              Store 118 116
             119:    7(fvec3) Load 91(c)
                              ReturnValue 119
                              FunctionEnd
32(grid_coord_to_grid_idx(u1;u1;u1;):     27(int) Function None 28
           29(i):     26(ptr) FunctionParameter
           30(j):     26(ptr) FunctionParameter
           31(k):     26(ptr) FunctionParameter
              33:             Label
             125:    124(ptr) AccessChain 44(ubo_in) 122 123
             126:     25(int) Load 125
             128:    124(ptr) AccessChain 44(ubo_in) 122 127
             129:     25(int) Load 128
             130:     25(int) IMul 126 129
             131:     25(int) Load 31(k)
             132:     25(int) IMul 130 131
             133:    124(ptr) AccessChain 44(ubo_in) 122 123
             134:     25(int) Load 133
             135:     25(int) Load 30(j)
             136:     25(int) IMul 134 135
             137:     25(int) IAdd 132 136
             138:     25(int) Load 29(i)
             139:     25(int) IAdd 137 138
             140:     27(int) Bitcast 139
                              ReturnValue 140
                              FunctionEnd
37(mark_skip_light(u1;vf3;):           2 Function None 34
   35(light_idx):     26(ptr) FunctionParameter
   36(light_pos):      8(ptr) FunctionParameter
              38:             Label
             146:         143 Load 145(light_pos_ranges)
             147:     25(int) Load 35(light_idx)
             148:     27(int) Bitcast 147
             149:    7(fvec3) Load 36(light_pos)
             150:    6(float) CompositeExtract 149 0
             151:    6(float) CompositeExtract 149 1
             152:    6(float) CompositeExtract 149 2
             153:   39(fvec4) CompositeConstruct 150 151 152 100
                              ImageWrite 146 148 153
                              Return
                              FunctionEnd
#endif

static const uint32_t calc_light_grids_comp[3241] = {
    0x07230203, 0x00010000, 0x00080001, 0x0000021b,
    0x00000000, 0x00020011, 0x00000001, 0x00020011,
    0x0000002f, 0x00020011, 0x00000031, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0006000f, 0x00000005, 0x00000004, 0x6e69616d,
    0x00000000, 0x0000009d, 0x00060010, 0x00000004,
    0x00000011, 0x00000020, 0x00000001, 0x00000001,
    0x00030003, 0x00000002, 0x000001c2, 0x00040005,
    0x00000004, 0x6e69616d, 0x00000000, 0x00080005,
    0x0000000b, 0x5f746567, 0x77656976, 0x6170735f,
    0x705f6563, 0x7628736f, 0x003b3366, 0x00040005,
    0x0000000a, 0x5f736f70, 0x00006e69, 0x00090005,
    0x00000010, 0x77656976, 0x736f705f, 0x5f6f745f,
    0x67617266, 0x736f705f, 0x33667628, 0x0000003b,
    0x00050005, 0x0000000f, 0x77656976, 0x736f705f,
    0x00000000, 0x000a0005, 0x00000017, 0x77656976,
    0x736f705f, 0x5f6f745f, 0x64697267, 0x6f6f635f,
    0x76286472, 0x663b3266, 0x00003b31, 0x00050005,
    0x00000015, 0x67617266, 0x736f705f, 0x00000000,
    0x00040005, 0x00000016, 0x77656976, 0x00007a5f,
    0x000b0005, 0x00000020, 0x64697267, 0x6f6f635f,
    0x745f6472, 0x72675f6f, 0x695f6469, 0x75287864,
    0x31753b31, 0x3b31753b, 0x00000000, 0x00030005,
    0x0000001d, 0x00000069, 0x00030005, 0x0000001e,
    0x0000006a, 0x00030005, 0x0000001f, 0x0000006b,
    0x00080005, 0x00000025, 0x6b72616d, 0x696b735f,
    0x696c5f70, 0x28746867, 0x763b3175, 0x003b3366,
    0x00050005, 0x00000023, 0x6867696c, 0x64695f74,
    0x00000078, 0x00050005, 0x00000024, 0x6867696c,
    0x6f705f74, 0x00000073, 0x00030005, 0x0000002a,
    0x004f4255, 0x00050006, 0x0000002a, 0x00000000,
    0x77656976, 0x00000000, 0x00050006, 0x0000002a,
    0x00000001, 0x6d726f6e, 0x00006c61, 0x00050006,
    0x0000002a, 0x00000002, 0x65646f6d, 0x0000006c,
    0x00070006, 0x0000002a, 0x00000003, 0x6a6f7270,
    0x69746365, 0x635f6e6f, 0x0070696c, 0x00060006,
    0x0000002a, 0x00000004, 0x656c6974, 0x7a69735f,
    0x00000065, 0x00060006, 0x0000002a, 0x00000005,
    0x64697267, 0x6d69645f, 0x00000000, 0x00050006,
    0x0000002a, 0x00000006, 0x5f6d6163, 0x00736f70,
    0x00050006, 0x0000002a, 0x00000007, 0x5f6d6163,
    0x00726166, 0x00060006, 0x0000002a, 0x00000008,
    0x6f736572, 0x6974756c, 0x00006e6f, 0x00060006,
    0x0000002a, 0x00000009, 0x5f6d756e, 0x6867696c,
    0x00007374, 0x00040005, 0x0000002c, 0x5f6f6275,
    0x00006e69, 0x00050005, 0x0000003c, 0x70696c63,
    0x736f705f, 0x00000000, 0x00030005, 0x00000046,
    0x0063646e, 0x00030005, 0x0000005b, 0x00000063,
    0x00070005, 0x00000091, 0x6867696c, 0x6f705f74,
    0x61725f73, 0x7365676e, 0x00000000, 0x00050005,
    0x0000009a, 0x6867696c, 0x64695f74, 0x00000078,
    0x00080005, 0x0000009d, 0x475f6c67, 0x61626f6c,
    0x766e496c, 0x7461636f, 0x496e6f69, 0x00000044,
    0x00060005, 0x000000a9, 0x5f736f70, 0x676e6172,
    0x6e695f65, 0x00000000, 0x00030005, 0x000000ae,
    0x00007076, 0x00040005, 0x000000af, 0x61726170,
    0x0000006d, 0x00040005, 0x000000b3, 0x6d5f7076,
    0x00006e69, 0x00040005, 0x000000ba, 0x6d5f7076,
    0x00007861, 0x00040005, 0x000000e1, 0x61726170,
    0x0000006d, 0x00040005, 0x000000e3, 0x61726170,
    0x0000006d, 0x00040005, 0x000000f3, 0x615f7066,
    0x00000000, 0x00040005, 0x000000fb, 0x61726170,
    0x0000006d, 0x00040005, 0x000000fd, 0x625f7066,
    0x00000000, 0x00040005, 0x00000105, 0x61726170,
    0x0000006d, 0x00040005, 0x00000107, 0x635f7066,
    0x00000000, 0x00040005, 0x0000010f, 0x61726170,
    0x0000006d, 0x00040005, 0x00000111, 0x645f7066,
    0x00000000, 0x00040005, 0x00000119, 0x61726170,
    0x0000006d, 0x00040005, 0x0000011b, 0x6d5f7066,
    0x00006e69, 0x00040005, 0x0000011f, 0x6d5f7066,
    0x00007861, 0x00040005, 0x00000124, 0x74697865,
    0x00000000, 0x00040005, 0x0000017a, 0x61726170,
    0x0000006d, 0x00040005, 0x0000017c, 0x61726170,
    0x0000006d, 0x00060005, 0x0000018a, 0x64697267,
    0x6f6f635f, 0x6d5f6472, 0x00006e69, 0x00040005,
    0x0000018b, 0x61726170, 0x0000006d, 0x00040005,
    0x0000018d, 0x61726170, 0x0000006d, 0x00060005,
    0x00000191, 0x64697267, 0x6f6f635f, 0x6d5f6472,
    0x00007861, 0x00040005, 0x00000192, 0x61726170,
    0x0000006d, 0x00040005, 0x00000194, 0x61726170,
    0x0000006d, 0x00050005, 0x00000199, 0x6e756f62,
    0x696d5f64, 0x0000006e, 0x00050005, 0x0000019c,
    0x6e756f62, 0x616d5f64, 0x00000078, 0x00060005,
    0x000001a1, 0x6867696c, 0x6f625f74, 0x73646e75,
    0x00000000, 0x00030005, 0x000001d6, 0x00000069,
    0x00030005, 0x000001e2, 0x0000006a, 0x00030005,
    0x000001ee, 0x0000006b, 0x00050005, 0x000001fb,
    0x64697267, 0x7864695f, 0x00000000, 0x00040005,
    0x000001fc, 0x61726170, 0x0000006d, 0x00040005,
    0x000001fe, 0x61726170, 0x0000006d, 0x00040005,
    0x00000200, 0x61726170, 0x0000006d, 0x00050005,
    0x00000205, 0x64697267, 0x616c665f, 0x00007367,
    0x00070005, 0x0000020d, 0x64697267, 0x67696c5f,
    0x635f7468, 0x746e756f, 0x00000073, 0x00040048,
    0x0000002a, 0x00000000, 0x00000005, 0x00050048,
    0x0000002a, 0x00000000, 0x00000023, 0x00000000,
    0x00050048, 0x0000002a, 0x00000000, 0x00000007,
    0x00000010, 0x00040048, 0x0000002a, 0x00000001,
    0x00000005, 0x00050048, 0x0000002a, 0x00000001,
    0x00000023, 0x00000040, 0x00050048, 0x0000002a,
    0x00000001, 0x00000007, 0x00000010, 0x00040048,
    0x0000002a, 0x00000002, 0x00000005, 0x00050048,
    0x0000002a, 0x00000002, 0x00000023, 0x00000080,
    0x00050048, 0x0000002a, 0x00000002, 0x00000007,
    0x00000010, 0x00040048, 0x0000002a, 0x00000003,
    0x00000005, 0x00050048, 0x0000002a, 0x00000003,
    0x00000023, 0x000000c0, 0x00050048, 0x0000002a,
    0x00000003, 0x00000007, 0x00000010, 0x00050048,
    0x0000002a, 0x00000004, 0x00000023, 0x00000100,
    0x00050048, 0x0000002a, 0x00000005, 0x00000023,
    0x00000108, 0x00050048, 0x0000002a, 0x00000006,
    0x00000023, 0x00000110, 0x00050048, 0x0000002a,
    0x00000007, 0x00000023, 0x0000011c, 0x00050048,
    0x0000002a, 0x00000008, 0x00000023, 0x00000120,
    0x00050048, 0x0000002a, 0x00000009, 0x00000023,
    0x00000128, 0x00030047, 0x0000002a, 0x00000002,
    0x00040047, 0x0000002c, 0x00000022, 0x00000000,
    0x00040047, 0x0000002c, 0x00000021, 0x00000000,
    0x00040047, 0x00000091, 0x00000022, 0x00000000,
    0x00040047, 0x00000091, 0x00000021, 0x00000001,
    0x00040047, 0x0000009d, 0x0000000b, 0x0000001c,
    0x00040047, 0x000001a1, 0x00000022, 0x00000001,
    0x00040047, 0x000001a1, 0x00000021, 0x00000001,
    0x00040047, 0x00000205, 0x00000022, 0x00000001,
    0x00040047, 0x00000205, 0x00000021, 0x00000000,
    0x00040047, 0x0000020d, 0x00000022, 0x00000001,
    0x00040047, 0x0000020d, 0x00000021, 0x00000002,
    0x00040047, 0x0000021a, 0x0000000b, 0x00000019,
    0x00020013, 0x00000002, 0x00030021, 0x00000003,
    0x00000002, 0x00030016, 0x00000006, 0x00000020,
    0x00040017, 0x00000007, 0x00000006, 0x00000003,
    0x00040020, 0x00000008, 0x00000007, 0x00000007,
    0x00040021, 0x00000009, 0x00000007, 0x00000008,
    0x00040017, 0x0000000d, 0x00000006, 0x00000002,
    0x00040021, 0x0000000e, 0x0000000d, 0x00000008,
    0x00040020, 0x00000012, 0x00000007, 0x0000000d,
    0x00040020, 0x00000013, 0x00000007, 0x00000006,
    0x00050021, 0x00000014, 0x00000007, 0x00000012,
    0x00000013, 0x00040015, 0x00000019, 0x00000020,
    0x00000000, 0x00040020, 0x0000001a, 0x00000007,
    0x00000019, 0x00040015, 0x0000001b, 0x00000020,
    0x00000001, 0x00060021, 0x0000001c, 0x0000001b,
    0x0000001a, 0x0000001a, 0x0000001a, 0x00050021,
    0x00000022, 0x00000002, 0x0000001a, 0x00000008,
    0x00040017, 0x00000027, 0x00000006, 0x00000004,
    0x00040018, 0x00000028, 0x00000027, 0x00000004,
    0x00040017, 0x00000029, 0x00000019, 0x00000002,
    0x000c001e, 0x0000002a, 0x00000028, 0x00000028,
    0x00000028, 0x00000028, 0x0000000d, 0x00000029,
    0x00000007, 0x00000006, 0x0000000d, 0x00000019,
    0x00040020, 0x0000002b, 0x00000002, 0x0000002a,
    0x0004003b, 0x0000002b, 0x0000002c, 0x00000002,
    0x0004002b, 0x0000001b, 0x0000002d, 0x00000000,
    0x00040020, 0x0000002e, 0x00000002, 0x00000028,
    0x0004002b, 0x00000006, 0x00000032, 0x3f800000,
    0x00040020, 0x0000003b, 0x00000007, 0x00000027,
    0x0004002b, 0x0000001b, 0x0000003d, 0x00000003,
    0x0004002b, 0x00000019, 0x00000049, 0x00000003,
    0x0004002b, 0x00000006, 0x0000004e, 0x3f000000,
    0x0004002b, 0x0000001b, 0x00000054, 0x00000008,
    0x00040020, 0x00000055, 0x00000002, 0x0000000d,
    0x0004002b, 0x0000001b, 0x0000005d, 0x00000004,
    0x0004002b, 0x00000006, 0x00000063, 0x437f0000,
    0x0004002b, 0x00000006, 0x00000064, 0x00000000,
    0x0004002b, 0x00000006, 0x00000065, 0x43800000,
    0x0004002b, 0x00000006, 0x00000068, 0x3dcccccd,
    0x0004002b, 0x0000001b, 0x0000006a, 0x00000007,
    0x00040020, 0x0000006b, 0x00000002, 0x00000006,
    0x0004002b, 0x00000019, 0x00000075, 0x00000002,
    0x0004002b, 0x0000001b, 0x0000007a, 0x00000005,
    0x0004002b, 0x00000019, 0x0000007b, 0x00000000,
    0x00040020, 0x0000007c, 0x00000002, 0x00000019,
    0x0004002b, 0x00000019, 0x0000007f, 0x00000001,
    0x00090019, 0x0000008f, 0x00000006, 0x00000005,
    0x00000000, 0x00000000, 0x00000000, 0x00000002,
    0x00000001, 0x00040020, 0x00000090, 0x00000000,
    0x0000008f, 0x0004003b, 0x00000090, 0x00000091,
    0x00000000, 0x00040017, 0x0000009b, 0x00000019,
    0x00000003, 0x00040020, 0x0000009c, 0x00000001,
    0x0000009b, 0x0004003b, 0x0000009c, 0x0000009d,
    0x00000001, 0x00040020, 0x0000009e, 0x00000001,
    0x00000019, 0x0004002b, 0x0000001b, 0x000000a2,
    0x00000009, 0x00020014, 0x000000a5, 0x0004002b,
    0x00000006, 0x000000d3, 0xbdcccccd, 0x00040020,
    0x00000123, 0x00000007, 0x000000a5, 0x0003002a,
    0x000000a5, 0x00000125, 0x0005002c, 0x0000000d,
    0x00000181, 0x00000064, 0x00000064, 0x00040020,
    0x00000198, 0x00000007, 0x0000009b, 0x00090019,
    0x0000019f, 0x00000019, 0x00000005, 0x00000000,
    0x00000000, 0x00000000, 0x00000002, 0x00000021,
    0x00040020, 0x000001a0, 0x00000000, 0x0000019f,
    0x0004003b, 0x000001a0, 0x000001a1, 0x00000000,
    0x0004002b, 0x00000019, 0x000001a4, 0x00000006,
    0x00040017, 0x000001aa, 0x00000019, 0x00000004,
    0x0004002b, 0x00000019, 0x000001c7, 0x00000004,
    0x0004002b, 0x00000019, 0x000001d0, 0x00000005,
    0x00040020, 0x000001fa, 0x00000007, 0x0000001b,
    0x00090019, 0x00000203, 0x00000019, 0x00000005,
    0x00000000, 0x00000000, 0x00000000, 0x00000002,
    0x00000027, 0x00040020, 0x00000204, 0x00000000,
    0x00000203, 0x0004003b, 0x00000204, 0x00000205,
    0x00000000, 0x0004003b, 0x000001a0, 0x0000020d,
    0x00000000, 0x00040020, 0x0000020f, 0x0000000b,
    0x00000019, 0x0004002b, 0x0000001b, 0x00000213,
    0x00000001, 0x0004002b, 0x00000019, 0x00000219,
    0x00000020, 0x0006002c, 0x0000009b, 0x0000021a,
    0x00000219, 0x0000007f, 0x0000007f, 0x00050036,
    0x00000002, 0x00000004, 0x00000000, 0x00000003,
    0x000200f8, 0x00000005, 0x0004003b, 0x0000001a,
    0x0000009a, 0x00000007, 0x0004003b, 0x0000003b,
    0x000000a9, 0x00000007, 0x0004003b, 0x00000008,
    0x000000ae, 0x00000007, 0x0004003b, 0x00000008,
    0x000000af, 0x00000007, 0x0004003b, 0x00000008,
    0x000000b3, 0x00000007, 0x0004003b, 0x00000008,
    0x000000ba, 0x00000007, 0x0004003b, 0x0000001a,
    0x000000e1, 0x00000007, 0x0004003b, 0x00000008,
    0x000000e3, 0x00000007, 0x0004003b, 0x00000012,
    0x000000f3, 0x00000007, 0x0004003b, 0x00000008,
    0x000000fb, 0x00000007, 0x0004003b, 0x00000012,
    0x000000fd, 0x00000007, 0x0004003b, 0x00000008,
    0x00000105, 0x00000007, 0x0004003b, 0x00000012,
    0x00000107, 0x00000007, 0x0004003b, 0x00000008,
    0x0000010f, 0x00000007, 0x0004003b, 0x00000012,
    0x00000111, 0x00000007, 0x0004003b, 0x00000008,
    0x00000119, 0x00000007, 0x0004003b, 0x00000012,
    0x0000011b, 0x00000007, 0x0004003b, 0x00000012,
    0x0000011f, 0x00000007, 0x0004003b, 0x00000123,
    0x00000124, 0x00000007, 0x0004003b, 0x0000001a,
    0x0000017a, 0x00000007, 0x0004003b, 0x00000008,
    0x0000017c, 0x00000007, 0x0004003b, 0x00000008,
    0x0000018a, 0x00000007, 0x0004003b, 0x00000012,
    0x0000018b, 0x00000007, 0x0004003b, 0x00000013,
    0x0000018d, 0x00000007, 0x0004003b, 0x00000008,
    0x00000191, 0x00000007, 0x0004003b, 0x00000012,
    0x00000192, 0x00000007, 0x0004003b, 0x00000013,
    0x00000194, 0x00000007, 0x0004003b, 0x00000198,
    0x00000199, 0x00000007, 0x0004003b, 0x00000198,
    0x0000019c, 0x00000007, 0x0004003b, 0x0000001a,
    0x000001d6, 0x00000007, 0x0004003b, 0x0000001a,
    0x000001e2, 0x00000007, 0x0004003b, 0x0000001a,
    0x000001ee, 0x00000007, 0x0004003b, 0x000001fa,
    0x000001fb, 0x00000007, 0x0004003b, 0x0000001a,
    0x000001fc, 0x00000007, 0x0004003b, 0x0000001a,
    0x000001fe, 0x00000007, 0x0004003b, 0x0000001a,
    0x00000200, 0x00000007, 0x00050041, 0x0000009e,
    0x0000009f, 0x0000009d, 0x0000007b, 0x0004003d,
    0x00000019, 0x000000a0, 0x0000009f, 0x0003003e,
    0x0000009a, 0x000000a0, 0x0004003d, 0x00000019,
    0x000000a1, 0x0000009a, 0x00050041, 0x0000007c,
    0x000000a3, 0x0000002c, 0x000000a2, 0x0004003d,
    0x00000019, 0x000000a4, 0x000000a3, 0x000500b0,
    0x000000a5, 0x000000a6, 0x000000a1, 0x000000a4,
    0x000300f7, 0x000000a8, 0x00000000, 0x000400fa,
    0x000000a6, 0x000000a7, 0x000000a8, 0x000200f8,
    0x000000a7, 0x0004003d, 0x0000008f, 0x000000aa,
    0x00000091, 0x0004003d, 0x00000019, 0x000000ab,
    0x0000009a, 0x0004007c, 0x0000001b, 0x000000ac,
    0x000000ab, 0x00050062, 0x00000027, 0x000000ad,
    0x000000aa, 0x000000ac, 0x0003003e, 0x000000a9,
    0x000000ad, 0x0004003d, 0x00000027, 0x000000b0,
    0x000000a9, 0x0008004f, 0x00000007, 0x000000b1,
    0x000000b0, 0x000000b0, 0x00000000, 0x00000001,
    0x00000002, 0x0003003e, 0x000000af, 0x000000b1,
    0x00050039, 0x00000007, 0x000000b2, 0x0000000b,
    0x000000af, 0x0003003e, 0x000000ae, 0x000000b2,
    0x00050041, 0x00000013, 0x000000b4, 0x000000ae,
    0x0000007b, 0x0004003d, 0x00000006, 0x000000b5,
    0x000000b4, 0x00050041, 0x00000013, 0x000000b6,
    0x000000a9, 0x00000049, 0x0004003d, 0x00000006,
    0x000000b7, 0x000000b6, 0x00050083, 0x00000006,
    0x000000b8, 0x000000b5, 0x000000b7, 0x00050041,
    0x00000013, 0x000000b9, 0x000000b3, 0x0000007b,
    0x0003003e, 0x000000b9, 0x000000b8, 0x00050041,
    0x00000013, 0x000000bb, 0x000000ae, 0x0000007b,
    0x0004003d, 0x00000006, 0x000000bc, 0x000000bb,
    0x00050041, 0x00000013, 0x000000bd, 0x000000a9,
    0x00000049, 0x0004003d, 0x00000006, 0x000000be,
    0x000000bd, 0x00050081, 0x00000006, 0x000000bf,
    0x000000bc, 0x000000be, 0x00050041, 0x00000013,
    0x000000c0, 0x000000ba, 0x0000007b, 0x0003003e,
    0x000000c0, 0x000000bf, 0x0004003d, 0x00000007,
    0x000000c1, 0x000000ae, 0x0007004f, 0x0000000d,
    0x000000c2, 0x000000c1, 0x000000c1, 0x00000001,
    0x00000002, 0x00050041, 0x00000013, 0x000000c3,
    0x000000a9, 0x00000049, 0x0004003d, 0x00000006,
    0x000000c4, 0x000000c3, 0x00050050, 0x0000000d,
    0x000000c5, 0x000000c4, 0x000000c4, 0x00050081,
    0x0000000d, 0x000000c6, 0x000000c2, 0x000000c5,
    0x0004003d, 0x00000007, 0x000000c7, 0x000000b3,
    0x0008004f, 0x00000007, 0x000000c8, 0x000000c7,
    0x000000c6, 0x00000000, 0x00000003, 0x00000004,
    0x0003003e, 0x000000b3, 0x000000c8, 0x0004003d,
    0x00000007, 0x000000c9, 0x000000ae, 0x0007004f,
    0x0000000d, 0x000000ca, 0x000000c9, 0x000000c9,
    0x00000001, 0x00000002, 0x00050041, 0x00000013,
    0x000000cb, 0x000000a9, 0x00000049, 0x0004003d,
    0x00000006, 0x000000cc, 0x000000cb, 0x00050050,
    0x0000000d, 0x000000cd, 0x000000cc, 0x000000cc,
    0x00050083, 0x0000000d, 0x000000ce, 0x000000ca,
    0x000000cd, 0x0004003d, 0x00000007, 0x000000cf,
    0x000000ba, 0x0008004f, 0x00000007, 0x000000d0,
    0x000000cf, 0x000000ce, 0x00000000, 0x00000003,
    0x00000004, 0x0003003e, 0x000000ba, 0x000000d0,
    0x00050041, 0x00000013, 0x000000d1, 0x000000ba,
    0x00000075, 0x0004003d, 0x00000006, 0x000000d2,
    0x000000d1, 0x000500be, 0x000000a5, 0x000000d4,
    0x000000d2, 0x000000d3, 0x000400a8, 0x000000a5,
    0x000000d5, 0x000000d4, 0x000300f7, 0x000000d7,
    0x00000000, 0x000400fa, 0x000000d5, 0x000000d6,
    0x000000d7, 0x000200f8, 0x000000d6, 0x00050041,
    0x00000013, 0x000000d8, 0x000000b3, 0x00000075,
    0x0004003d, 0x00000006, 0x000000d9, 0x000000d8,
    0x00050041, 0x0000006b, 0x000000da, 0x0000002c,
    0x0000006a, 0x0004003d, 0x00000006, 0x000000db,
    0x000000da, 0x0004007f, 0x00000006, 0x000000dc,
    0x000000db, 0x000500bc, 0x000000a5, 0x000000dd,
    0x000000d9, 0x000000dc, 0x000200f9, 0x000000d7,
    0x000200f8, 0x000000d7, 0x000700f5, 0x000000a5,
    0x000000de, 0x000000d4, 0x000000a7, 0x000000dd,
    0x000000d6, 0x000300f7, 0x000000e0, 0x00000000,
    0x000400fa, 0x000000de, 0x000000df, 0x000000e0,
    0x000200f8, 0x000000df, 0x0004003d, 0x00000019,
    0x000000e2, 0x0000009a, 0x0003003e, 0x000000e1,
    0x000000e2, 0x0004003d, 0x00000027, 0x000000e4,
    0x000000a9, 0x0008004f, 0x00000007, 0x000000e5,
    0x000000e4, 0x000000e4, 0x00000000, 0x00000001,
    0x00000002, 0x0003003e, 0x000000e3, 0x000000e5,
    0x00060039, 0x00000002, 0x000000e6, 0x00000025,
    0x000000e1, 0x000000e3, 0x000100fd, 0x000200f8,
    0x000000e0, 0x00050041, 0x00000013, 0x000000e8,
    0x000000b3, 0x00000075, 0x0004003d, 0x00000006,
    0x000000e9, 0x000000e8, 0x0007000c, 0x00000006,
    0x000000ea, 0x00000001, 0x00000025, 0x000000d3,
    0x000000e9, 0x00050041, 0x00000013, 0x000000eb,
    0x000000b3, 0x00000075, 0x0003003e, 0x000000eb,
    0x000000ea, 0x00050041, 0x0000006b, 0x000000ec,
    0x0000002c, 0x0000006a, 0x0004003d, 0x00000006,
    0x000000ed, 0x000000ec, 0x0004007f, 0x00000006,
    0x000000ee, 0x000000ed, 0x00050041, 0x00000013,
    0x000000ef, 0x000000ba, 0x00000075, 0x0004003d,
    0x00000006, 0x000000f0, 0x000000ef, 0x0007000c,
    0x00000006, 0x000000f1, 0x00000001, 0x00000028,
    0x000000ee, 0x000000f0, 0x00050041, 0x00000013,
    0x000000f2, 0x000000ba, 0x00000075, 0x0003003e,
    0x000000f2, 0x000000f1, 0x0004003d, 0x00000007,
    0x000000f4, 0x000000b3, 0x0007004f, 0x0000000d,
    0x000000f5, 0x000000f4, 0x000000f4, 0x00000000,
    0x00000001, 0x00050041, 0x00000013, 0x000000f6,
    0x000000b3, 0x00000075, 0x0004003d, 0x00000006,
    0x000000f7, 0x000000f6, 0x00050051, 0x00000006,
    0x000000f8, 0x000000f5, 0x00000000, 0x00050051,
    0x00000006, 0x000000f9, 0x000000f5, 0x00000001,
    0x00060050, 0x00000007, 0x000000fa, 0x000000f8,
    0x000000f9, 0x000000f7, 0x0003003e, 0x000000fb,
    0x000000fa, 0x00050039, 0x0000000d, 0x000000fc,
    0x00000010, 0x000000fb, 0x0003003e, 0x000000f3,
    0x000000fc, 0x0004003d, 0x00000007, 0x000000fe,
    0x000000b3, 0x0007004f, 0x0000000d, 0x000000ff,
    0x000000fe, 0x000000fe, 0x00000000, 0x00000001,
    0x00050041, 0x00000013, 0x00000100, 0x000000ba,
    0x00000075, 0x0004003d, 0x00000006, 0x00000101,
    0x00000100, 0x00050051, 0x00000006, 0x00000102,
    0x000000ff, 0x00000000, 0x00050051, 0x00000006,
    0x00000103, 0x000000ff, 0x00000001, 0x00060050,
    0x00000007, 0x00000104, 0x00000102, 0x00000103,
    0x00000101, 0x0003003e, 0x00000105, 0x00000104,
    0x00050039, 0x0000000d, 0x00000106, 0x00000010,
    0x00000105, 0x0003003e, 0x000000fd, 0x00000106,
    0x0004003d, 0x00000007, 0x00000108, 0x000000ba,
    0x0007004f, 0x0000000d, 0x00000109, 0x00000108,
    0x00000108, 0x00000000, 0x00000001, 0x00050041,
    0x00000013, 0x0000010a, 0x000000ba, 0x00000075,
    0x0004003d, 0x00000006, 0x0000010b, 0x0000010a,
    0x00050051, 0x00000006, 0x0000010c, 0x00000109,
    0x00000000, 0x00050051, 0x00000006, 0x0000010d,
    0x00000109, 0x00000001, 0x00060050, 0x00000007,
    0x0000010e, 0x0000010c, 0x0000010d, 0x0000010b,
    0x0003003e, 0x0000010f, 0x0000010e, 0x00050039,
    0x0000000d, 0x00000110, 0x00000010, 0x0000010f,
    0x0003003e, 0x00000107, 0x00000110, 0x0004003d,
    0x00000007, 0x00000112, 0x000000ba, 0x0007004f,
    0x0000000d, 0x00000113, 0x00000112, 0x00000112,
    0x00000000, 0x00000001, 0x00050041, 0x00000013,
    0x00000114, 0x000000b3, 0x00000075, 0x0004003d,
    0x00000006, 0x00000115, 0x00000114, 0x00050051,
    0x00000006, 0x00000116, 0x00000113, 0x00000000,
    0x00050051, 0x00000006, 0x00000117, 0x00000113,
    0x00000001, 0x00060050, 0x00000007, 0x00000118,
    0x00000116, 0x00000117, 0x00000115, 0x0003003e,
    0x00000119, 0x00000118, 0x00050039, 0x0000000d,
    0x0000011a, 0x00000010, 0x00000119, 0x0003003e,
    0x00000111, 0x0000011a, 0x0004003d, 0x0000000d,
    0x0000011c, 0x000000f3, 0x0004003d, 0x0000000d,
    0x0000011d, 0x000000fd, 0x0007000c, 0x0000000d,
    0x0000011e, 0x00000001, 0x00000025, 0x0000011c,
    0x0000011d, 0x0003003e, 0x0000011b, 0x0000011e,
    0x0004003d, 0x0000000d, 0x00000120, 0x00000107,
    0x0004003d, 0x0000000d, 0x00000121, 0x00000111,
    0x0007000c, 0x0000000d, 0x00000122, 0x00000001,
    0x00000028, 0x00000120, 0x00000121, 0x0003003e,
    0x0000011f, 0x00000122, 0x0003003e, 0x00000124,
    0x00000125, 0x0004003d, 0x000000a5, 0x00000126,
    0x00000124, 0x000400a8, 0x000000a5, 0x00000127,
    0x00000126, 0x000300f7, 0x00000129, 0x00000000,
    0x000400fa, 0x00000127, 0x00000128, 0x00000129,
    0x000200f8, 0x00000128, 0x00050041, 0x00000013,
    0x0000012a, 0x0000011b, 0x0000007b, 0x0004003d,
    0x00000006, 0x0000012b, 0x0000012a, 0x000500b8,
    0x000000a5, 0x0000012c, 0x0000012b, 0x00000064,
    0x000300f7, 0x0000012e, 0x00000000, 0x000400fa,
    0x0000012c, 0x0000012d, 0x0000012e, 0x000200f8,
    0x0000012d, 0x00050041, 0x00000013, 0x0000012f,
    0x0000011f, 0x0000007b, 0x0004003d, 0x00000006,
    0x00000130, 0x0000012f, 0x000500b8, 0x000000a5,
    0x00000131, 0x00000130, 0x00000064, 0x000200f9,
    0x0000012e, 0x000200f8, 0x0000012e, 0x000700f5,
    0x000000a5, 0x00000132, 0x0000012c, 0x00000128,
    0x00000131, 0x0000012d, 0x000200f9, 0x00000129,
    0x000200f8, 0x00000129, 0x000700f5, 0x000000a5,
    0x00000133, 0x00000126, 0x000000e0, 0x00000132,
    0x0000012e, 0x000400a8, 0x000000a5, 0x00000134,
    0x00000133, 0x000300f7, 0x00000136, 0x00000000,
    0x000400fa, 0x00000134, 0x00000135, 0x00000136,
    0x000200f8, 0x00000135, 0x00050041, 0x00000013,
    0x00000137, 0x0000011b, 0x0000007f, 0x0004003d,
    0x00000006, 0x00000138, 0x00000137, 0x000500b8,
    0x000000a5, 0x00000139, 0x00000138, 0x00000064,
    0x000300f7, 0x0000013b, 0x00000000, 0x000400fa,
    0x00000139, 0x0000013a, 0x0000013b, 0x000200f8,
    0x0000013a, 0x00050041, 0x00000013, 0x0000013c,
    0x0000011f, 0x0000007f, 0x0004003d, 0x00000006,
    0x0000013d, 0x0000013c, 0x000500b8, 0x000000a5,
    0x0000013e, 0x0000013d, 0x00000064, 0x000200f9,
    0x0000013b, 0x000200f8, 0x0000013b, 0x000700f5,
    0x000000a5, 0x0000013f, 0x00000139, 0x00000135,
    0x0000013e, 0x0000013a, 0x000200f9, 0x00000136,
    0x000200f8, 0x00000136, 0x000700f5, 0x000000a5,
    0x00000140, 0x00000133, 0x00000129, 0x0000013f,
    0x0000013b, 0x0003003e, 0x00000124, 0x00000140,
    0x0004003d, 0x000000a5, 0x00000141, 0x00000124,
    0x000400a8, 0x000000a5, 0x00000142, 0x00000141,
    0x000300f7, 0x00000144, 0x00000000, 0x000400fa,
    0x00000142, 0x00000143, 0x00000144, 0x000200f8,
    0x00000143, 0x00050041, 0x00000013, 0x00000145,
    0x0000011b, 0x0000007b, 0x0004003d, 0x00000006,
    0x00000146, 0x00000145, 0x00060041, 0x0000006b,
    0x00000147, 0x0000002c, 0x00000054, 0x0000007b,
    0x0004003d, 0x00000006, 0x00000148, 0x00000147,
    0x000500be, 0x000000a5, 0x00000149, 0x00000146,
    0x00000148, 0x000300f7, 0x0000014b, 0x00000000,
    0x000400fa, 0x00000149, 0x0000014a, 0x0000014b,
    0x000200f8, 0x0000014a, 0x00050041, 0x00000013,
    0x0000014c, 0x0000011f, 0x0000007b, 0x0004003d,
    0x00000006, 0x0000014d, 0x0000014c, 0x00060041,
    0x0000006b, 0x0000014e, 0x0000002c, 0x00000054,
    0x0000007b, 0x0004003d, 0x00000006, 0x0000014f,
    0x0000014e, 0x000500be, 0x000000a5, 0x00000150,
    0x0000014d, 0x0000014f, 0x000200f9, 0x0000014b,
    0x000200f8, 0x0000014b, 0x000700f5, 0x000000a5,
    0x00000151, 0x00000149, 0x00000143, 0x00000150,
    0x0000014a, 0x000200f9, 0x00000144, 0x000200f8,
    0x00000144, 0x000700f5, 0x000000a5, 0x00000152,
    0x00000141, 0x00000136, 0x00000151, 0x0000014b,
    0x000400a8, 0x000000a5, 0x00000153, 0x00000152,
    0x000300f7, 0x00000155, 0x00000000, 0x000400fa,
    0x00000153, 0x00000154, 0x00000155, 0x000200f8,
    0x00000154, 0x00050041, 0x00000013, 0x00000156,
    0x0000011b, 0x0000007f, 0x0004003d, 0x00000006,
    0x00000157, 0x00000156, 0x00060041, 0x0000006b,
    0x00000158, 0x0000002c, 0x00000054, 0x0000007f,
    0x0004003d, 0x00000006, 0x00000159, 0x00000158,
    0x000500be, 0x000000a5, 0x0000015a, 0x00000157,
    0x00000159, 0x000300f7, 0x0000015c, 0x00000000,
    0x000400fa, 0x0000015a, 0x0000015b, 0x0000015c,
    0x000200f8, 0x0000015b, 0x00050041, 0x00000013,
    0x0000015d, 0x0000011f, 0x0000007f, 0x0004003d,
    0x00000006, 0x0000015e, 0x0000015d, 0x00060041,
    0x0000006b, 0x0000015f, 0x0000002c, 0x00000054,
    0x0000007f, 0x0004003d, 0x00000006, 0x00000160,
    0x0000015f, 0x000500be, 0x000000a5, 0x00000161,
    0x0000015e, 0x00000160, 0x000200f9, 0x0000015c,
    0x000200f8, 0x0000015c, 0x000700f5, 0x000000a5,
    0x00000162, 0x0000015a, 0x00000154, 0x00000161,
    0x0000015b, 0x000200f9, 0x00000155, 0x000200f8,
    0x00000155, 0x000700f5, 0x000000a5, 0x00000163,
    0x00000152, 0x00000144, 0x00000162, 0x0000015c,
    0x0003003e, 0x00000124, 0x00000163, 0x0004003d,
    0x000000a5, 0x00000164, 0x00000124, 0x000400a8,
    0x000000a5, 0x00000165, 0x00000164, 0x000300f7,
    0x00000167, 0x00000000, 0x000400fa, 0x00000165,
    0x00000166, 0x00000167, 0x000200f8, 0x00000166,
    0x00050041, 0x00000013, 0x00000168, 0x0000011b,
    0x0000007b, 0x0004003d, 0x00000006, 0x00000169,
    0x00000168, 0x00050041, 0x00000013, 0x0000016a,
    0x0000011f, 0x0000007b, 0x0004003d, 0x00000006,
    0x0000016b, 0x0000016a, 0x000500ba, 0x000000a5,
    0x0000016c, 0x00000169, 0x0000016b, 0x000200f9,
    0x00000167, 0x000200f8, 0x00000167, 0x000700f5,
    0x000000a5, 0x0000016d, 0x00000164, 0x00000155,
    0x0000016c, 0x00000166, 0x000400a8, 0x000000a5,
    0x0000016e, 0x0000016d, 0x000300f7, 0x00000170,
    0x00000000, 0x000400fa, 0x0000016e, 0x0000016f,
    0x00000170, 0x000200f8, 0x0000016f, 0x00050041,
    0x00000013, 0x00000171, 0x0000011b, 0x0000007f,
    0x0004003d, 0x00000006, 0x00000172, 0x00000171,
    0x00050041, 0x00000013, 0x00000173, 0x0000011f,
    0x0000007f, 0x0004003d, 0x00000006, 0x00000174,
    0x00000173, 0x000500ba, 0x000000a5, 0x00000175,
    0x00000172, 0x00000174, 0x000200f9, 0x00000170,
    0x000200f8, 0x00000170, 0x000700f5, 0x000000a5,
    0x00000176, 0x0000016d, 0x00000167, 0x00000175,
    0x0000016f, 0x0003003e, 0x00000124, 0x00000176,
    0x0004003d, 0x000000a5, 0x00000177, 0x00000124,
    0x000300f7, 0x00000179, 0x00000000, 0x000400fa,
    0x00000177, 0x00000178, 0x00000179, 0x000200f8,
    0x00000178, 0x0004003d, 0x00000019, 0x0000017b,
    0x0000009a, 0x0003003e, 0x0000017a, 0x0000017b,
    0x0004003d, 0x00000027, 0x0000017d, 0x000000a9,
    0x0008004f, 0x00000007, 0x0000017e, 0x0000017d,
    0x0000017d, 0x00000000, 0x00000001, 0x00000002,
    0x0003003e, 0x0000017c, 0x0000017e, 0x00060039,
    0x00000002, 0x0000017f, 0x00000025, 0x0000017a,
    0x0000017c, 0x000100fd, 0x000200f8, 0x00000179,
    0x0004003d, 0x0000000d, 0x00000182, 0x0000011b,
    0x0007000c, 0x0000000d, 0x00000183, 0x00000001,
    0x00000028, 0x00000181, 0x00000182, 0x0003003e,
    0x0000011b, 0x00000183, 0x00050041, 0x00000055,
    0x00000184, 0x0000002c, 0x00000054, 0x0004003d,
    0x0000000d, 0x00000185, 0x00000184, 0x00050050,
    0x0000000d, 0x00000186, 0x00000032, 0x00000032,
    0x00050083, 0x0000000d, 0x00000187, 0x00000185,
    0x00000186, 0x0004003d, 0x0000000d, 0x00000188,
    0x0000011f, 0x0007000c, 0x0000000d, 0x00000189,
    0x00000001, 0x00000025, 0x00000187, 0x00000188,
    0x0003003e, 0x0000011f, 0x00000189, 0x0004003d,
    0x0000000d, 0x0000018c, 0x0000011b, 0x0003003e,
    0x0000018b, 0x0000018c, 0x00050041, 0x00000013,
    0x0000018e, 0x000000b3, 0x00000075, 0x0004003d,
    0x00000006, 0x0000018f, 0x0000018e, 0x0003003e,
    0x0000018d, 0x0000018f, 0x00060039, 0x00000007,
    0x00000190, 0x00000017, 0x0000018b, 0x0000018d,
    0x0003003e, 0x0000018a, 0x00000190, 0x0004003d,
    0x0000000d, 0x00000193, 0x0000011f, 0x0003003e,
    0x00000192, 0x00000193, 0x00050041, 0x00000013,
    0x00000195, 0x000000ba, 0x00000075, 0x0004003d,
    0x00000006, 0x00000196, 0x00000195, 0x0003003e,
    0x00000194, 0x00000196, 0x00060039, 0x00000007,
    0x00000197, 0x00000017, 0x00000192, 0x00000194,
    0x0003003e, 0x00000191, 0x00000197, 0x0004003d,
    0x00000007, 0x0000019a, 0x0000018a, 0x0004006d,
    0x0000009b, 0x0000019b, 0x0000019a, 0x0003003e,
    0x00000199, 0x0000019b, 0x0004003d, 0x00000007,
    0x0000019d, 0x00000191, 0x0004006d, 0x0000009b,
    0x0000019e, 0x0000019d, 0x0003003e, 0x0000019c,
    0x0000019e, 0x0004003d, 0x0000019f, 0x000001a2,
    0x000001a1, 0x0004003d, 0x00000019, 0x000001a3,
    0x0000009a, 0x00050084, 0x00000019, 0x000001a5,
    0x000001a3, 0x000001a4, 0x00050080, 0x00000019,
    0x000001a6, 0x000001a5, 0x0000007b, 0x0004007c,
    0x0000001b, 0x000001a7, 0x000001a6, 0x00050041,
    0x0000001a, 0x000001a8, 0x00000199, 0x0000007b,
    0x0004003d, 0x00000019, 0x000001a9, 0x000001a8,
    0x00070050, 0x000001aa, 0x000001ab, 0x000001a9,
    0x0000007b, 0x0000007b, 0x0000007b, 0x00040063,
    0x000001a2, 0x000001a7, 0x000001ab, 0x0004003d,
    0x0000019f, 0x000001ac, 0x000001a1, 0x0004003d,
    0x00000019, 0x000001ad, 0x0000009a, 0x00050084,
    0x00000019, 0x000001ae, 0x000001ad, 0x000001a4,
    0x00050080, 0x00000019, 0x000001af, 0x000001ae,
    0x0000007f, 0x0004007c, 0x0000001b, 0x000001b0,
    0x000001af, 0x00050041, 0x0000001a, 0x000001b1,
    0x00000199, 0x0000007f, 0x0004003d, 0x00000019,
    0x000001b2, 0x000001b1, 0x00070050, 0x000001aa,
    0x000001b3, 0x000001b2, 0x0000007b, 0x0000007b,
    0x0000007b, 0x00040063, 0x000001ac, 0x000001b0,
    0x000001b3, 0x0004003d, 0x0000019f, 0x000001b4,
    0x000001a1, 0x0004003d, 0x00000019, 0x000001b5,
    0x0000009a, 0x00050084, 0x00000019, 0x000001b6,
    0x000001b5, 0x000001a4, 0x00050080, 0x00000019,
    0x000001b7, 0x000001b6, 0x00000075, 0x0004007c,
    0x0000001b, 0x000001b8, 0x000001b7, 0x00050041,
    0x0000001a, 0x000001b9, 0x00000199, 0x00000075,
    0x0004003d, 0x00000019, 0x000001ba, 0x000001b9,
    0x00070050, 0x000001aa, 0x000001bb, 0x000001ba,
    0x0000007b, 0x0000007b, 0x0000007b, 0x00040063,
    0x000001b4, 0x000001b8, 0x000001bb, 0x0004003d,
    0x0000019f, 0x000001bc, 0x000001a1, 0x0004003d,
    0x00000019, 0x000001bd, 0x0000009a, 0x00050084,
    0x00000019, 0x000001be, 0x000001bd, 0x000001a4,
    0x00050080, 0x00000019, 0x000001bf, 0x000001be,
    0x00000049, 0x0004007c, 0x0000001b, 0x000001c0,
    0x000001bf, 0x00050041, 0x0000001a, 0x000001c1,
    0x0000019c, 0x0000007b, 0x0004003d, 0x00000019,
    0x000001c2, 0x000001c1, 0x00070050, 0x000001aa,
    0x000001c3, 0x000001c2, 0x0000007b, 0x0000007b,
    0x0000007b, 0x00040063, 0x000001bc, 0x000001c0,
    0x000001c3, 0x0004003d, 0x0000019f, 0x000001c4,
    0x000001a1, 0x0004003d, 0x00000019, 0x000001c5,
    0x0000009a, 0x00050084, 0x00000019, 0x000001c6,
    0x000001c5, 0x000001a4, 0x00050080, 0x00000019,
    0x000001c8, 0x000001c6, 0x000001c7, 0x0004007c,
    0x0000001b, 0x000001c9, 0x000001c8, 0x00050041,
    0x0000001a, 0x000001ca, 0x0000019c, 0x0000007f,
    0x0004003d, 0x00000019, 0x000001cb, 0x000001ca,
    0x00070050, 0x000001aa, 0x000001cc, 0x000001cb,
    0x0000007b, 0x0000007b, 0x0000007b, 0x00040063,
    0x000001c4, 0x000001c9, 0x000001cc, 0x0004003d,
    0x0000019f, 0x000001cd, 0x000001a1, 0x0004003d,
    0x00000019, 0x000001ce, 0x0000009a, 0x00050084,
    0x00000019, 0x000001cf, 0x000001ce, 0x000001a4,
    0x00050080, 0x00000019, 0x000001d1, 0x000001cf,
    0x000001d0, 0x0004007c, 0x0000001b, 0x000001d2,
    0x000001d1, 0x00050041, 0x0000001a, 0x000001d3,
    0x0000019c, 0x00000075, 0x0004003d, 0x00000019,
    0x000001d4, 0x000001d3, 0x00070050, 0x000001aa,
    0x000001d5, 0x000001d4, 0x0000007b, 0x0000007b,
    0x0000007b, 0x00040063, 0x000001cd, 0x000001d2,
    0x000001d5, 0x00050041, 0x0000001a, 0x000001d7,
    0x00000199, 0x0000007b, 0x0004003d, 0x00000019,
    0x000001d8, 0x000001d7, 0x0003003e, 0x000001d6,
    0x000001d8, 0x000200f9, 0x000001d9, 0x000200f8,
    0x000001d9, 0x000400f6, 0x000001db, 0x000001dc,
    0x00000000, 0x000200f9, 0x000001dd, 0x000200f8,
    0x000001dd, 0x0004003d, 0x00000019, 0x000001de,
    0x000001d6, 0x00050041, 0x0000001a, 0x000001df,
    0x0000019c, 0x0000007b, 0x0004003d, 0x00000019,
    0x000001e0, 0x000001df, 0x000500b2, 0x000000a5,
    0x000001e1, 0x000001de, 0x000001e0, 0x000400fa,
    0x000001e1, 0x000001da, 0x000001db, 0x000200f8,
    0x000001da, 0x00050041, 0x0000001a, 0x000001e3,
    0x00000199, 0x0000007f, 0x0004003d, 0x00000019,
    0x000001e4, 0x000001e3, 0x0003003e, 0x000001e2,
    0x000001e4, 0x000200f9, 0x000001e5, 0x000200f8,
    0x000001e5, 0x000400f6, 0x000001e7, 0x000001e8,
    0x00000000, 0x000200f9, 0x000001e9, 0x000200f8,
    0x000001e9, 0x0004003d, 0x00000019, 0x000001ea,
    0x000001e2, 0x00050041, 0x0000001a, 0x000001eb,
    0x0000019c, 0x0000007f, 0x0004003d, 0x00000019,
    0x000001ec, 0x000001eb, 0x000500b2, 0x000000a5,
    0x000001ed, 0x000001ea, 0x000001ec, 0x000400fa,
    0x000001ed, 0x000001e6, 0x000001e7, 0x000200f8,
    0x000001e6, 0x00050041, 0x0000001a, 0x000001ef,
    0x00000199, 0x00000075, 0x0004003d, 0x00000019,
    0x000001f0, 0x000001ef, 0x0003003e, 0x000001ee,
    0x000001f0, 0x000200f9, 0x000001f1, 0x000200f8,
    0x000001f1, 0x000400f6, 0x000001f3, 0x000001f4,
    0x00000000, 0x000200f9, 0x000001f5, 0x000200f8,
    0x000001f5, 0x0004003d, 0x00000019, 0x000001f6,
    0x000001ee, 0x00050041, 0x0000001a, 0x000001f7,
    0x0000019c, 0x00000075, 0x0004003d, 0x00000019,
    0x000001f8, 0x000001f7, 0x000500b2, 0x000000a5,
    0x000001f9, 0x000001f6, 0x000001f8, 0x000400fa,
    0x000001f9, 0x000001f2, 0x000001f3, 0x000200f8,
    0x000001f2, 0x0004003d, 0x00000019, 0x000001fd,
    0x000001d6, 0x0003003e, 0x000001fc, 0x000001fd,
    0x0004003d, 0x00000019, 0x000001ff, 0x000001e2,
    0x0003003e, 0x000001fe, 0x000001ff, 0x0004003d,
    0x00000019, 0x00000201, 0x000001ee, 0x0003003e,
    0x00000200, 0x00000201, 0x00070039, 0x0000001b,
    0x00000202, 0x00000020, 0x000001fc, 0x000001fe,
    0x00000200, 0x0003003e, 0x000001fb, 0x00000202,
    0x0004003d, 0x00000203, 0x00000206, 0x00000205,
    0x0004003d, 0x0000001b, 0x00000207, 0x000001fb,
    0x00050062, 0x000001aa, 0x00000208, 0x00000206,
    0x00000207, 0x00050051, 0x00000019, 0x00000209,
    0x00000208, 0x00000000, 0x000500aa, 0x000000a5,
    0x0000020a, 0x00000209, 0x0000007f, 0x000300f7,
    0x0000020c, 0x00000000, 0x000400fa, 0x0000020a,
    0x0000020b, 0x0000020c, 0x000200f8, 0x0000020b,
    0x0004003d, 0x0000001b, 0x0000020e, 0x000001fb,
    0x0006003c, 0x0000020f, 0x00000210, 0x0000020d,
    0x0000020e, 0x0000007b, 0x000700ea, 0x00000019,
    0x00000211, 0x00000210, 0x0000007f, 0x0000007b,
    0x0000007f, 0x000200f9, 0x0000020c, 0x000200f8,
    0x0000020c, 0x000200f9, 0x000001f4, 0x000200f8,
    0x000001f4, 0x0004003d, 0x00000019, 0x00000212,
    0x000001ee, 0x00050080, 0x00000019, 0x00000214,
    0x00000212, 0x00000213, 0x0003003e, 0x000001ee,
    0x00000214, 0x000200f9, 0x000001f1, 0x000200f8,
    0x000001f3, 0x000200f9, 0x000001e8, 0x000200f8,
    0x000001e8, 0x0004003d, 0x00000019, 0x00000215,
    0x000001e2, 0x00050080, 0x00000019, 0x00000216,
    0x00000215, 0x00000213, 0x0003003e, 0x000001e2,
    0x00000216, 0x000200f9, 0x000001e5, 0x000200f8,
    0x000001e7, 0x000200f9, 0x000001dc, 0x000200f8,
    0x000001dc, 0x0004003d, 0x00000019, 0x00000217,
    0x000001d6, 0x00050080, 0x00000019, 0x00000218,
    0x00000217, 0x00000213, 0x0003003e, 0x000001d6,
    0x00000218, 0x000200f9, 0x000001d9, 0x000200f8,
    0x000001db, 0x000200f9, 0x000000a8, 0x000200f8,
    0x000000a8, 0x000100fd, 0x00010038, 0x00050036,
    0x00000007, 0x0000000b, 0x00000000, 0x00000009,
    0x00030037, 0x00000008, 0x0000000a, 0x000200f8,
    0x0000000c, 0x00050041, 0x0000002e, 0x0000002f,
    0x0000002c, 0x0000002d, 0x0004003d, 0x00000028,
    0x00000030, 0x0000002f, 0x0004003d, 0x00000007,
    0x00000031, 0x0000000a, 0x00050051, 0x00000006,
    0x00000033, 0x00000031, 0x00000000, 0x00050051,
    0x00000006, 0x00000034, 0x00000031, 0x00000001,
    0x00050051, 0x00000006, 0x00000035, 0x00000031,
    0x00000002, 0x00070050, 0x00000027, 0x00000036,
    0x00000033, 0x00000034, 0x00000035, 0x00000032,
    0x00050091, 0x00000027, 0x00000037, 0x00000030,
    0x00000036, 0x0008004f, 0x00000007, 0x00000038,
    0x00000037, 0x00000037, 0x00000000, 0x00000001,
    0x00000002, 0x000200fe, 0x00000038, 0x00010038,
    0x00050036, 0x0000000d, 0x00000010, 0x00000000,
    0x0000000e, 0x00030037, 0x00000008, 0x0000000f,
    0x000200f8, 0x00000011, 0x0004003b, 0x0000003b,
    0x0000003c, 0x00000007, 0x0004003b, 0x00000008,
    0x00000046, 0x00000007, 0x00050041, 0x0000002e,
    0x0000003e, 0x0000002c, 0x0000003d, 0x0004003d,
    0x00000028, 0x0000003f, 0x0000003e, 0x0004003d,
    0x00000007, 0x00000040, 0x0000000f, 0x00050051,
    0x00000006, 0x00000041, 0x00000040, 0x00000000,
    0x00050051, 0x00000006, 0x00000042, 0x00000040,
    0x00000001, 0x00050051, 0x00000006, 0x00000043,
    0x00000040, 0x00000002, 0x00070050, 0x00000027,
    0x00000044, 0x00000041, 0x00000042, 0x00000043,
    0x00000032, 0x00050091, 0x00000027, 0x00000045,
    0x0000003f, 0x00000044, 0x0003003e, 0x0000003c,
    0x00000045, 0x0004003d, 0x00000027, 0x00000047,
    0x0000003c, 0x0008004f, 0x00000007, 0x00000048,
    0x00000047, 0x00000047, 0x00000000, 0x00000001,
    0x00000002, 0x00050041, 0x00000013, 0x0000004a,
    0x0000003c, 0x00000049, 0x0004003d, 0x00000006,
    0x0000004b, 0x0000004a, 0x00060050, 0x00000007,
    0x0000004c, 0x0000004b, 0x0000004b, 0x0000004b,
    0x00050088, 0x00000007, 0x0000004d, 0x00000048,
    0x0000004c, 0x0003003e, 0x00000046, 0x0000004d,
    0x0004003d, 0x00000007, 0x0000004f, 0x00000046,
    0x0007004f, 0x0000000d, 0x00000050, 0x0000004f,
    0x0000004f, 0x00000000, 0x00000001, 0x00050050,
    0x0000000d, 0x00000051, 0x00000032, 0x00000032,
    0x00050081, 0x0000000d, 0x00000052, 0x00000051,
    0x00000050, 0x0005008e, 0x0000000d, 0x00000053,
    0x00000052, 0x0000004e, 0x00050041, 0x00000055,
    0x00000056, 0x0000002c, 0x00000054, 0x0004003d,
    0x0000000d, 0x00000057, 0x00000056, 0x00050085,
    0x0000000d, 0x00000058, 0x00000053, 0x00000057,
    0x000200fe, 0x00000058, 0x00010038, 0x00050036,
    0x00000007, 0x00000017, 0x00000000, 0x00000014,
    0x00030037, 0x00000012, 0x00000015, 0x00030037,
    0x00000013, 0x00000016, 0x000200f8, 0x00000018,
    0x0004003b, 0x00000008, 0x0000005b, 0x00000007,
    0x0004003d, 0x0000000d, 0x0000005c, 0x00000015,
    0x00050041, 0x00000055, 0x0000005e, 0x0000002c,
    0x0000005d, 0x0004003d, 0x0000000d, 0x0000005f,
    0x0000005e, 0x00050088, 0x0000000d, 0x00000060,
    0x0000005c, 0x0000005f, 0x0004003d, 0x00000007,
    0x00000061, 0x0000005b, 0x0008004f, 0x00000007,
    0x00000062, 0x00000061, 0x00000060, 0x00000003,
    0x00000004, 0x00000002, 0x0003003e, 0x0000005b,
    0x00000062, 0x0004003d, 0x00000006, 0x00000066,
    0x00000016, 0x0004007f, 0x00000006, 0x00000067,
    0x00000066, 0x00050083, 0x00000006, 0x00000069,
    0x00000067, 0x00000068, 0x00050041, 0x0000006b,
    0x0000006c, 0x0000002c, 0x0000006a, 0x0004003d,
    0x00000006, 0x0000006d, 0x0000006c, 0x00050083,
    0x00000006, 0x0000006e, 0x0000006d, 0x00000068,
    0x00050088, 0x00000006, 0x0000006f, 0x00000069,
    0x0000006e, 0x00050081, 0x00000006, 0x00000070,
    0x0000006f, 0x00000032, 0x0006000c, 0x00000006,
    0x00000071, 0x00000001, 0x0000001c, 0x00000070,
    0x00050085, 0x00000006, 0x00000072, 0x00000065,
    0x00000071, 0x0007000c, 0x00000006, 0x00000073,
    0x00000001, 0x00000028, 0x00000064, 0x00000072,
    0x0007000c, 0x00000006, 0x00000074, 0x00000001,
    0x00000025, 0x00000063, 0x00000073, 0x00050041,
    0x00000013, 0x00000076, 0x0000005b, 0x00000075,
    0x0003003e, 0x00000076, 0x00000074, 0x0004003d,
    0x00000007, 0x00000077, 0x0000005b, 0x000200fe,
    0x00000077, 0x00010038, 0x00050036, 0x0000001b,
    0x00000020, 0x00000000, 0x0000001c, 0x00030037,
    0x0000001a, 0x0000001d, 0x00030037, 0x0000001a,
    0x0000001e, 0x00030037, 0x0000001a, 0x0000001f,
    0x000200f8, 0x00000021, 0x00060041, 0x0000007c,
    0x0000007d, 0x0000002c, 0x0000007a, 0x0000007b,
    0x0004003d, 0x00000019, 0x0000007e, 0x0000007d,
    0x00060041, 0x0000007c, 0x00000080, 0x0000002c,
    0x0000007a, 0x0000007f, 0x0004003d, 0x00000019,
    0x00000081, 0x00000080, 0x00050084, 0x00000019,
    0x00000082, 0x0000007e, 0x00000081, 0x0004003d,
    0x00000019, 0x00000083, 0x0000001f, 0x00050084,
    0x00000019, 0x00000084, 0x00000082, 0x00000083,
    0x00060041, 0x0000007c, 0x00000085, 0x0000002c,
    0x0000007a, 0x0000007b, 0x0004003d, 0x00000019,
    0x00000086, 0x00000085, 0x0004003d, 0x00000019,
    0x00000087, 0x0000001e, 0x00050084, 0x00000019,
    0x00000088, 0x00000086, 0x00000087, 0x00050080,
    0x00000019, 0x00000089, 0x00000084, 0x00000088,
    0x0004003d, 0x00000019, 0x0000008a, 0x0000001d,
    0x00050080, 0x00000019, 0x0000008b, 0x00000089,
    0x0000008a, 0x0004007c, 0x0000001b, 0x0000008c,
    0x0000008b, 0x000200fe, 0x0000008c, 0x00010038,
    0x00050036, 0x00000002, 0x00000025, 0x00000000,
    0x00000022, 0x00030037, 0x0000001a, 0x00000023,
    0x00030037, 0x00000008, 0x00000024, 0x000200f8,
    0x00000026, 0x0004003d, 0x0000008f, 0x00000092,
    0x00000091, 0x0004003d, 0x00000019, 0x00000093,
    0x00000023, 0x0004007c, 0x0000001b, 0x00000094,
    0x00000093, 0x0004003d, 0x00000007, 0x00000095,
    0x00000024, 0x00050051, 0x00000006, 0x00000096,
    0x00000095, 0x00000000, 0x00050051, 0x00000006,
    0x00000097, 0x00000095, 0x00000001, 0x00050051,
    0x00000006, 0x00000098, 0x00000095, 0x00000002,
    0x00070050, 0x00000027, 0x00000099, 0x00000096,
    0x00000097, 0x00000098, 0x00000064, 0x00040063,
    0x00000092, 0x00000094, 0x00000099, 0x000100fd,
    0x00010038,
};
