#include <stdint.h>

#if 0
C:/msys64/home/sydlu/CProjects/clustered-forward-demo-vk/demo/calc_light_list.comp
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 212

                              Capability Shader
                              Capability ImageBuffer
                              Capability StorageImageExtendedFormats
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint GLCompute 4  "main" 48
                              ExecutionMode 4 LocalSize 32 1 1
                              Source GLSL 450
                              Name 4  "main"
                              Name 13  "grid_coord_to_grid_idx(u1;u1;u1;"
                              Name 10  "i"
                              Name 11  "j"
                              Name 12  "k"
                              Name 21  "UBO"
                              MemberName 21(UBO) 0  "view"
                              MemberName 21(UBO) 1  "normal"
                              MemberName 21(UBO) 2  "model"
                              MemberName 21(UBO) 3  "projection_clip"
                              MemberName 21(UBO) 4  "tile_size"
                              MemberName 21(UBO) 5  "grid_dim"
                              MemberName 21(UBO) 6  "cam_pos"
                              MemberName 21(UBO) 7  "cam_far"
                              MemberName 21(UBO) 8  "resolution"
                              MemberName 21(UBO) 9  "num_lights"
                              Name 23  "ubo_in"
                              Name 45  "light_idx"
                              Name 48  "gl_GlobalInvocationID"
                              Name 61  "pos_range_in"
                              Name 64  "light_pos_ranges"
                              Name 78  "i_min"
                              Name 81  "light_bounds"
                              Name 91  "j_min"
                              Name 99  "k_min"
                              Name 108  "i_max"
                              Name 116  "j_max"
                              Name 125  "k_max"
                              Name 134  "i"
                              Name 144  "j"
                              Name 154  "k"
                              Name 165  "grid_idx"
                              Name 166  "param"
                              Name 168  "param"
                              Name 170  "param"
                              Name 175  "grid_flags"
                              Name 183  "offset"
                              Name 184  "grid_light_count_offsets"
                              Name 189  "grid_light_idx"
                              Name 190  "grid_light_counts_compare"
                              Name 195  "light_list"
                              MemberDecorate 21(UBO) 0 ColMajor
                              MemberDecorate 21(UBO) 0 Offset 0
                              MemberDecorate 21(UBO) 0 MatrixStride 16
                              MemberDecorate 21(UBO) 1 ColMajor
                              MemberDecorate 21(UBO) 1 Offset 64
                              MemberDecorate 21(UBO) 1 MatrixStride 16
                              MemberDecorate 21(UBO) 2 ColMajor
                              MemberDecorate 21(UBO) 2 Offset 128
                              MemberDecorate 21(UBO) 2 MatrixStride 16
                              MemberDecorate 21(UBO) 3 ColMajor
                              MemberDecorate 21(UBO) 3 Offset 192
                              MemberDecorate 21(UBO) 3 MatrixStride 16
                              MemberDecorate 21(UBO) 4 Offset 256
                              MemberDecorate 21(UBO) 5 Offset 264
                              MemberDecorate 21(UBO) 6 Offset 272
                              MemberDecorate 21(UBO) 7 Offset 284
                              MemberDecorate 21(UBO) 8 Offset 288
                              MemberDecorate 21(UBO) 9 Offset 296
                              Decorate 21(UBO) Block
                              Decorate 23(ubo_in) DescriptorSet 0
                              Decorate 23(ubo_in) Binding 0
                              Decorate 48(gl_GlobalInvocationID) BuiltIn GlobalInvocationId
                              Decorate 64(light_pos_ranges) DescriptorSet 0
                              Decorate 64(light_pos_ranges) Binding 1
                              Decorate 81(light_bounds) DescriptorSet 1
                              Decorate 81(light_bounds) Binding 1
                              Decorate 175(grid_flags) DescriptorSet 1
                              Decorate 175(grid_flags) Binding 0
                              Decorate 184(grid_light_count_offsets) DescriptorSet 1
                              Decorate 184(grid_light_count_offsets) Binding 4
                              Decorate 190(grid_light_counts_compare) DescriptorSet 1
                              Decorate 190(grid_light_counts_compare) Binding 6
                              Decorate 195(light_list) DescriptorSet 1
                              Decorate 195(light_list) Binding 5
                              Decorate 211 BuiltIn WorkgroupSize
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeInt 32 0
               7:             TypePointer Function 6(int)
               8:             TypeInt 32 1
               9:             TypeFunction 8(int) 7(ptr) 7(ptr) 7(ptr)
              15:             TypeFloat 32
              16:             TypeVector 15(float) 4
              17:             TypeMatrix 16(fvec4) 4
              18:             TypeVector 15(float) 2
              19:             TypeVector 6(int) 2
              20:             TypeVector 15(float) 3
         21(UBO):             TypeStruct 17 17 17 17 18(fvec2) 19(ivec2) 20(fvec3) 15(float) 18(fvec2) 6(int)
              22:             TypePointer Uniform 21(UBO)
      23(ubo_in):     22(ptr) Variable Uniform
              24:      8(int) Constant 5
              25:      6(int) Constant 0
              26:             TypePointer Uniform 6(int)
              29:      6(int) Constant 1
              46:             TypeVector 6(int) 3
              47:             TypePointer Input 46(ivec3)
48(gl_GlobalInvocationID):     47(ptr) Variable Input
              49:             TypePointer Input 6(int)
              53:      8(int) Constant 9
              56:             TypeBool
              60:             TypePointer Function 16(fvec4)
              62:             TypeImage 15(float) Buffer nonsampled format:Rgba32f
              63:             TypePointer UniformConstant 62
64(light_pos_ranges):     63(ptr) Variable UniformConstant
              69:      6(int) Constant 3
              70:             TypePointer Function 15(float)
              73:   15(float) Constant 0
              79:             TypeImage 6(int) Buffer nonsampled format:R32ui
              80:             TypePointer UniformConstant 79
81(light_bounds):     80(ptr) Variable UniformConstant
              84:      6(int) Constant 6
              88:             TypeVector 6(int) 4
             103:      6(int) Constant 2
             120:      6(int) Constant 4
             129:      6(int) Constant 5
             164:             TypePointer Function 8(int)
             173:             TypeImage 6(int) Buffer nonsampled format:R8ui
             174:             TypePointer UniformConstant 173
 175(grid_flags):    174(ptr) Variable UniformConstant
184(grid_light_count_offsets):     80(ptr) Variable UniformConstant
190(grid_light_counts_compare):     80(ptr) Variable UniformConstant
             192:             TypePointer Image 6(int)
 195(light_list):     80(ptr) Variable UniformConstant
             204:      8(int) Constant 1
             210:      6(int) Constant 32
             211:   46(ivec3) ConstantComposite 210 29 29
         4(main):           2 Function None 3
               5:             Label
   45(light_idx):      7(ptr) Variable Function
61(pos_range_in):     60(ptr) Variable Function
       78(i_min):      7(ptr) Variable Function
       91(j_min):      7(ptr) Variable Function
       99(k_min):      7(ptr) Variable Function
      108(i_max):      7(ptr) Variable Function
      116(j_max):      7(ptr) Variable Function
      125(k_max):      7(ptr) Variable Function
          134(i):      7(ptr) Variable Function
          144(j):      7(ptr) Variable Function
          154(k):      7(ptr) Variable Function
   165(grid_idx):    164(ptr) Variable Function
      166(param):      7(ptr) Variable Function
      168(param):      7(ptr) Variable Function
      170(param):      7(ptr) Variable Function
     183(offset):      7(ptr) Variable Function
189(grid_light_idx):      7(ptr) Variable Function
              50:     49(ptr) AccessChain 48(gl_GlobalInvocationID) 25
              51:      6(int) Load 50
                              Store 45(light_idx) 51
              52:      6(int) Load 45(light_idx)
              54:     26(ptr) AccessChain 23(ubo_in) 53
              55:      6(int) Load 54
              57:    56(bool) ULessThan 52 55
                              SelectionMerge 59 None
                              BranchConditional 57 58 59
              58:               Label
              65:          62   Load 64(light_pos_ranges)
              66:      6(int)   Load 45(light_idx)
              67:      8(int)   Bitcast 66
              68:   16(fvec4)   ImageRead 65 67
                                Store 61(pos_range_in) 68
              71:     70(ptr)   AccessChain 61(pos_range_in) 69
              72:   15(float)   Load 71
              74:    56(bool)   FOrdEqual 72 73
                                SelectionMerge 76 None
                                BranchConditional 74 75 76
              75:                 Label
                                  Return
              76:               Label
              82:          79   Load 81(light_bounds)
              83:      6(int)   Load 45(light_idx)
              85:      6(int)   IMul 83 84
              86:      6(int)   IAdd 85 25
              87:      8(int)   Bitcast 86
              89:   88(ivec4)   ImageRead 82 87
              90:      6(int)   CompositeExtract 89 0
                                Store 78(i_min) 90
              92:          79   Load 81(light_bounds)
              93:      6(int)   Load 45(light_idx)
              94:      6(int)   IMul 93 84
              95:      6(int)   IAdd 94 29
              96:      8(int)   Bitcast 95
              97:   88(ivec4)   ImageRead 92 96
              98:      6(int)   CompositeExtract 97 0
                                Store 91(j_min) 98
             100:          79   Load 81(light_bounds)
             101:      6(int)   Load 45(light_idx)
             102:      6(int)   IMul 101 84
             104:      6(int)   IAdd 102 103
             105:      8(int)   Bitcast 104
             106:   88(ivec4)   ImageRead 100 105
             107:      6(int)   CompositeExtract 106 0
                                Store 99(k_min) 107
             109:          79   Load 81(light_bounds)
             110:      6(int)   Load 45(light_idx)
             111:      6(int)   IMul 110 84
             112:      6(int)   IAdd 111 69
             113:      8(int)   Bitcast 112
             114:   88(ivec4)   ImageRead 109 113
             115:      6(int)   CompositeExtract 114 0
                                Store 108(i_max) 115
             117:          79   Load 81(light_bounds)
             118:      6(int)   Load 45(light_idx)
             119:      6(int)   IMul 118 84
             121:      6(int)   IAdd 119 120
             122:      8(int)   Bitcast 121
             123:   88(ivec4)   ImageRead 117 122
             124:      6(int)   CompositeExtract 123 0
                                Store 116(j_max) 124
             126:          79   Load 81(light_bounds)
             127:      6(int)   Load 45(light_idx)
             128:      6(int)   IMul 127 84
             130:      6(int)   IAdd 128 129
             131:      8(int)   Bitcast 130
             132:   88(ivec4)   ImageRead 126 131
             133:      6(int)   CompositeExtract 132 0
                                Store 125(k_max) 133
             135:      6(int)   Load 78(i_min)
                                Store 134(i) 135
                                Branch 136
             136:               Label
                                LoopMerge 138 139 None
                                Branch 140
             140:               Label
             141:      6(int)   Load 134(i)
             142:      6(int)   Load 108(i_max)
             143:    56(bool)   ULessThanEqual 141 142
                                BranchConditional 143 137 138
             137:                 Label
             145:      6(int)     Load 91(j_min)
                                  Store 144(j) 145
                                  Branch 146
             146:                 Label
                                  LoopMerge 148 149 None
                                  Branch 150
             150:                 Label
             151:      6(int)     Load 144(j)
             152:      6(int)     Load 116(j_max)
             153:    56(bool)     ULessThanEqual 151 152
                                  BranchConditional 153 147 148
             147:                   Label
             155:      6(int)       Load 99(k_min)
                                    Store 154(k) 155
                                    Branch 156
             156:                   Label
                                    LoopMerge 158 159 None
                                    Branch 160
             160:                   Label
             161:      6(int)       Load 154(k)
             162:      6(int)       Load 125(k_max)
             163:    56(bool)       ULessThanEqual 161 162
                                    BranchConditional 163 157 158
             157:                     Label
             167:      6(int)         Load 134(i)
                                      Store 166(param) 167
             169:      6(int)         Load 144(j)
                                      Store 168(param) 169
             171:      6(int)         Load 154(k)
                                      Store 170(param) 171
             172:      8(int)         FunctionCall 13(grid_coord_to_grid_idx(u1;u1;u1;) 166(param) 168(param) 170(param)
                                      Store 165(grid_idx) 172
             176:         173         Load 175(grid_flags)
             177:      8(int)         Load 165(grid_idx)
             178:   88(ivec4)         ImageRead 176 177
             179:      6(int)         CompositeExtract 178 0
             180:    56(bool)         IEqual 179 29
                                      SelectionMerge 182 None
                                      BranchConditional 180 181 182
             181:                       Label
             185:          79           Load 184(grid_light_count_offsets)
             186:      8(int)           Load 165(grid_idx)
             187:   88(ivec4)           ImageRead 185 186
             188:      6(int)           CompositeExtract 187 0
                                        Store 183(offset) 188
             191:      8(int)           Load 165(grid_idx)
             193:    192(ptr)           ImageTexelPointer 190(grid_light_counts_compare) 191 25
             194:      6(int)           AtomicIAdd 193 29 25 29
                                        Store 189(grid_light_idx) 194
             196:          79           Load 195(light_list)
             197:      6(int)           Load 183(offset)
             198:      6(int)           Load 189(grid_light_idx)
             199:      6(int)           IAdd 197 198
             200:      8(int)           Bitcast 199
             201:      6(int)           Load 45(light_idx)
             202:   88(ivec4)           CompositeConstruct 201 25 25 25
                                        ImageWrite 196 200 202
                                        Branch 182
             182:                     Label
                                      Branch 159
             159:                     Label
             203:      6(int)         Load 154(k)
             205:      6(int)         IAdd 203 204
                                      Store 154(k) 205
                                      Branch 156
             158:                   Label
                                    Branch 149
             149:                   Label
             206:      6(int)       Load 144(j)
             207:      6(int)       IAdd 206 204
                                    Store 144(j) 207
                                    Branch 146
             148:                 Label
                                  Branch 139
             139:                 Label
             208:      6(int)     Load 134(i)
             209:      6(int)     IAdd 208 204
                                  Store 134(i) 209
                                  Branch 136
             138:               Label
                                Branch 59
              59:             Label
                              Return
                              FunctionEnd
13(grid_coord_to_grid_idx(u1;u1;u1;):      8(int) Function None 9
           10(i):      7(ptr) FunctionParameter
           11(j):      7(ptr) FunctionParameter
           12(k):      7(ptr) FunctionParameter
              14:             Label
              27:     26(ptr) AccessChain 23(ubo_in) 24 25
              28:      6(int) Load 27
              30:     26(ptr) AccessChain 23(ubo_in) 24 29
              31:      6(int) Load 30
              32:      6(int) IMul 28 31
              33:      6(int) Load 12(k)
              34:      6(int) IMul 32 33
              35:     26(ptr) AccessChain 23(ubo_in) 24 25
              36:      6(int) Load 35
              37:      6(int) Load 11(j)
              38:      6(int) IMul 36 37
              39:      6(int) IAdd 34 38
              40:      6(int) Load 10(i)
              41:      6(int) IAdd 39 40
              42:      8(int) Bitcast 41
                              ReturnValue 42
                              FunctionEnd
#endif

static const uint32_t calc_light_list_comp[1404] = {
    0x07230203, 0x00010000, 0x00080001, 0x000000d4,
    0x00000000, 0x00020011, 0x00000001, 0x00020011,
    0x0000002f, 0x00020011, 0x00000031, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0006000f, 0x00000005, 0x00000004, 0x6e69616d,
    0x00000000, 0x00000030, 0x00060010, 0x00000004,
    0x00000011, 0x00000020, 0x00000001, 0x00000001,
    0x00030003, 0x00000002, 0x000001c2, 0x00040005,
    0x00000004, 0x6e69616d, 0x00000000, 0x000b0005,
    0x0000000d, 0x64697267, 0x6f6f635f, 0x745f6472,
    0x72675f6f, 0x695f6469, 0x75287864, 0x31753b31,
    0x3b31753b, 0x00000000, 0x00030005, 0x0000000a,
    0x00000069, 0x00030005, 0x0000000b, 0x0000006a,
    0x00030005, 0x0000000c, 0x0000006b, 0x00030005,
    0x00000015, 0x004f4255, 0x00050006, 0x00000015,
    0x00000000, 0x77656976, 0x00000000, 0x00050006,
    0x00000015, 0x00000001, 0x6d726f6e, 0x00006c61,
    0x00050006, 0x00000015, 0x00000002, 0x65646f6d,
    0x0000006c, 0x00070006, 0x00000015, 0x00000003,
    0x6a6f7270, 0x69746365, 0x635f6e6f, 0x0070696c,
    0x00060006, 0x00000015, 0x00000004, 0x656c6974,
    0x7a69735f, 0x00000065, 0x00060006, 0x00000015,
    0x00000005, 0x64697267, 0x6d69645f, 0x00000000,
    0x00050006, 0x00000015, 0x00000006, 0x5f6d6163,
    0x00736f70, 0x00050006, 0x00000015, 0x00000007,
    0x5f6d6163, 0x00726166, 0x00060006, 0x00000015,
    0x00000008, 0x6f736572, 0x6974756c, 0x00006e6f,
    0x00060006, 0x00000015, 0x00000009, 0x5f6d756e,
    0x6867696c, 0x00007374, 0x00040005, 0x00000017,
    0x5f6f6275, 0x00006e69, 0x00050005, 0x0000002d,
    0x6867696c, 0x64695f74, 0x00000078, 0x00080005,
    0x00000030, 0x475f6c67, 0x61626f6c, 0x766e496c,
    0x7461636f, 0x496e6f69, 0x00000044, 0x00060005,
    0x0000003d, 0x5f736f70, 0x676e6172, 0x6e695f65,
    0x00000000, 0x00070005, 0x00000040, 0x6867696c,
    0x6f705f74, 0x61725f73, 0x7365676e, 0x00000000,
    0x00040005, 0x0000004e, 0x696d5f69, 0x0000006e,
    0x00060005, 0x00000051, 0x6867696c, 0x6f625f74,
    0x73646e75, 0x00000000, 0x00040005, 0x0000005b,
    0x696d5f6a, 0x0000006e, 0x00040005, 0x00000063,
    0x696d5f6b, 0x0000006e, 0x00040005, 0x0000006c,
    0x616d5f69, 0x00000078, 0x00040005, 0x00000074,
    0x616d5f6a, 0x00000078, 0x00040005, 0x0000007d,
    0x616d5f6b, 0x00000078, 0x00030005, 0x00000086,
    0x00000069, 0x00030005, 0x00000090, 0x0000006a,
    0x00030005, 0x0000009a, 0x0000006b, 0x00050005,
    0x000000a5, 0x64697267, 0x7864695f, 0x00000000,
    0x00040005, 0x000000a6, 0x61726170, 0x0000006d,
    0x00040005, 0x000000a8, 0x61726170, 0x0000006d,
    0x00040005, 0x000000aa, 0x61726170, 0x0000006d,
    0x00050005, 0x000000af, 0x64697267, 0x616c665f,
    0x00007367, 0x00040005, 0x000000b7, 0x7366666f,
    0x00007465, 0x00090005, 0x000000b8, 0x64697267,
    0x67696c5f, 0x635f7468, 0x746e756f, 0x66666f5f,
    0x73746573, 0x00000000, 0x00060005, 0x000000bd,
    0x64697267, 0x67696c5f, 0x695f7468, 0x00007864,
    0x00090005, 0x000000be, 0x64697267, 0x67696c5f,
    0x635f7468, 0x746e756f, 0x6f635f73, 0x7261706d,
    0x00000065, 0x00050005, 0x000000c3, 0x6867696c,
    0x696c5f74, 0x00007473, 0x00040048, 0x00000015,
    0x00000000, 0x00000005, 0x00050048, 0x00000015,
    0x00000000, 0x00000023, 0x00000000, 0x00050048,
    0x00000015, 0x00000000, 0x00000007, 0x00000010,
    0x00040048, 0x00000015, 0x00000001, 0x00000005,
    0x00050048, 0x00000015, 0x00000001, 0x00000023,
    0x00000040, 0x00050048, 0x00000015, 0x00000001,
    0x00000007, 0x00000010, 0x00040048, 0x00000015,
    0x00000002, 0x00000005, 0x00050048, 0x00000015,
    0x00000002, 0x00000023, 0x00000080, 0x00050048,
    0x00000015, 0x00000002, 0x00000007, 0x00000010,
    0x00040048, 0x00000015, 0x00000003, 0x00000005,
    0x00050048, 0x00000015, 0x00000003, 0x00000023,
    0x000000c0, 0x00050048, 0x00000015, 0x00000003,
    0x00000007, 0x00000010, 0x00050048, 0x00000015,
    0x00000004, 0x00000023, 0x00000100, 0x00050048,
    0x00000015, 0x00000005, 0x00000023, 0x00000108,
    0x00050048, 0x00000015, 0x00000006, 0x00000023,
    0x00000110, 0x00050048, 0x00000015, 0x00000007,
    0x00000023, 0x0000011c, 0x00050048, 0x00000015,
    0x00000008, 0x00000023, 0x00000120, 0x00050048,
    0x00000015, 0x00000009, 0x00000023, 0x00000128,
    0x00030047, 0x00000015, 0x00000002, 0x00040047,
    0x00000017, 0x00000022, 0x00000000, 0x00040047,
    0x00000017, 0x00000021, 0x00000000, 0x00040047,
    0x00000030, 0x0000000b, 0x0000001c, 0x00040047,
    0x00000040, 0x00000022, 0x00000000, 0x00040047,
    0x00000040, 0x00000021, 0x00000001, 0x00040047,
    0x00000051, 0x00000022, 0x00000001, 0x00040047,
    0x00000051, 0x00000021, 0x00000001, 0x00040047,
    0x000000af, 0x00000022, 0x00000001, 0x00040047,
    0x000000af, 0x00000021, 0x00000000, 0x00040047,
    0x000000b8, 0x00000022, 0x00000001, 0x00040047,
    0x000000b8, 0x00000021, 0x00000004, 0x00040047,
    0x000000be, 0x00000022, 0x00000001, 0x00040047,
    0x000000be, 0x00000021, 0x00000006, 0x00040047,
    0x000000c3, 0x00000022, 0x00000001, 0x00040047,
    0x000000c3, 0x00000021, 0x00000005, 0x00040047,
    0x000000d3, 0x0000000b, 0x00000019, 0x00020013,
    0x00000002, 0x00030021, 0x00000003, 0x00000002,
    0x00040015, 0x00000006, 0x00000020, 0x00000000,
    0x00040020, 0x00000007, 0x00000007, 0x00000006,
    0x00040015, 0x00000008, 0x00000020, 0x00000001,
    0x00060021, 0x00000009, 0x00000008, 0x00000007,
    0x00000007, 0x00000007, 0x00030016, 0x0000000f,
    0x00000020, 0x00040017, 0x00000010, 0x0000000f,
    0x00000004, 0x00040018, 0x00000011, 0x00000010,
    0x00000004, 0x00040017, 0x00000012, 0x0000000f,
    0x00000002, 0x00040017, 0x00000013, 0x00000006,
    0x00000002, 0x00040017, 0x00000014, 0x0000000f,
    0x00000003, 0x000c001e, 0x00000015, 0x00000011,
    0x00000011, 0x00000011, 0x00000011, 0x00000012,
    0x00000013, 0x00000014, 0x0000000f, 0x00000012,
    0x00000006, 0x00040020, 0x00000016, 0x00000002,
    0x00000015, 0x0004003b, 0x00000016, 0x00000017,
    0x00000002, 0x0004002b, 0x00000008, 0x00000018,
    0x00000005, 0x0004002b, 0x00000006, 0x00000019,
    0x00000000, 0x00040020, 0x0000001a, 0x00000002,
    0x00000006, 0x0004002b, 0x00000006, 0x0000001d,
    0x00000001, 0x00040017, 0x0000002e, 0x00000006,
    0x00000003, 0x00040020, 0x0000002f, 0x00000001,
    0x0000002e, 0x0004003b, 0x0000002f, 0x00000030,
    0x00000001, 0x00040020, 0x00000031, 0x00000001,
    0x00000006, 0x0004002b, 0x00000008, 0x00000035,
    0x00000009, 0x00020014, 0x00000038, 0x00040020,
    0x0000003c, 0x00000007, 0x00000010, 0x00090019,
    0x0000003e, 0x0000000f, 0x00000005, 0x00000000,
    0x00000000, 0x00000000, 0x00000002, 0x00000001,
    0x00040020, 0x0000003f, 0x00000000, 0x0000003e,
    0x0004003b, 0x0000003f, 0x00000040, 0x00000000,
    0x0004002b, 0x00000006, 0x00000045, 0x00000003,
    0x00040020, 0x00000046, 0x00000007, 0x0000000f,
    0x0004002b, 0x0000000f, 0x00000049, 0x00000000,
    0x00090019, 0x0000004f, 0x00000006, 0x00000005,
    0x00000000, 0x00000000, 0x00000000, 0x00000002,
    0x00000021, 0x00040020, 0x00000050, 0x00000000,
    0x0000004f, 0x0004003b, 0x00000050, 0x00000051,
    0x00000000, 0x0004002b, 0x00000006, 0x00000054,
    0x00000006, 0x00040017, 0x00000058, 0x00000006,
    0x00000004, 0x0004002b, 0x00000006, 0x00000067,
    0x00000002, 0x0004002b, 0x00000006, 0x00000078,
    0x00000004, 0x0004002b, 0x00000006, 0x00000081,
    0x00000005, 0x00040020, 0x000000a4, 0x00000007,
    0x00000008, 0x00090019, 0x000000ad, 0x00000006,
    0x00000005, 0x00000000, 0x00000000, 0x00000000,
    0x00000002, 0x00000027, 0x00040020, 0x000000ae,
    0x00000000, 0x000000ad, 0x0004003b, 0x000000ae,
    0x000000af, 0x00000000, 0x0004003b, 0x00000050,
    0x000000b8, 0x00000000, 0x0004003b, 0x00000050,
    0x000000be, 0x00000000, 0x00040020, 0x000000c0,
    0x0000000b, 0x00000006, 0x0004003b, 0x00000050,
    0x000000c3, 0x00000000, 0x0004002b, 0x00000008,
    0x000000cc, 0x00000001, 0x0004002b, 0x00000006,
    0x000000d2, 0x00000020, 0x0006002c, 0x0000002e,
    0x000000d3, 0x000000d2, 0x0000001d, 0x0000001d,
    0x00050036, 0x00000002, 0x00000004, 0x00000000,
    0x00000003, 0x000200f8, 0x00000005, 0x0004003b,
    0x00000007, 0x0000002d, 0x00000007, 0x0004003b,
    0x0000003c, 0x0000003d, 0x00000007, 0x0004003b,
    0x00000007, 0x0000004e, 0x00000007, 0x0004003b,
    0x00000007, 0x0000005b, 0x00000007, 0x0004003b,
    0x00000007, 0x00000063, 0x00000007, 0x0004003b,
    0x00000007, 0x0000006c, 0x00000007, 0x0004003b,
    0x00000007, 0x00000074, 0x00000007, 0x0004003b,
    0x00000007, 0x0000007d, 0x00000007, 0x0004003b,
    0x00000007, 0x00000086, 0x00000007, 0x0004003b,
    0x00000007, 0x00000090, 0x00000007, 0x0004003b,
    0x00000007, 0x0000009a, 0x00000007, 0x0004003b,
    0x000000a4, 0x000000a5, 0x00000007, 0x0004003b,
    0x00000007, 0x000000a6, 0x00000007, 0x0004003b,
    0x00000007, 0x000000a8, 0x00000007, 0x0004003b,
    0x00000007, 0x000000aa, 0x00000007, 0x0004003b,
    0x00000007, 0x000000b7, 0x00000007, 0x0004003b,
    0x00000007, 0x000000bd, 0x00000007, 0x00050041,
    0x00000031, 0x00000032, 0x00000030, 0x00000019,
    0x0004003d, 0x00000006, 0x00000033, 0x00000032,
    0x0003003e, 0x0000002d, 0x00000033, 0x0004003d,
    0x00000006, 0x00000034, 0x0000002d, 0x00050041,
    0x0000001a, 0x00000036, 0x00000017, 0x00000035,
    0x0004003d, 0x00000006, 0x00000037, 0x00000036,
    0x000500b0, 0x00000038, 0x00000039, 0x00000034,
    0x00000037, 0x000300f7, 0x0000003b, 0x00000000,
    0x000400fa, 0x00000039, 0x0000003a, 0x0000003b,
    0x000200f8, 0x0000003a, 0x0004003d, 0x0000003e,
    0x00000041, 0x00000040, 0x0004003d, 0x00000006,
    0x00000042, 0x0000002d, 0x0004007c, 0x00000008,
    0x00000043, 0x00000042, 0x00050062, 0x00000010,
    0x00000044, 0x00000041, 0x00000043, 0x0003003e,
    0x0000003d, 0x00000044, 0x00050041, 0x00000046,
    0x00000047, 0x0000003d, 0x00000045, 0x0004003d,
    0x0000000f, 0x00000048, 0x00000047, 0x000500b4,
    0x00000038, 0x0000004a, 0x00000048, 0x00000049,
    0x000300f7, 0x0000004c, 0x00000000, 0x000400fa,
    0x0000004a, 0x0000004b, 0x0000004c, 0x000200f8,
    0x0000004b, 0x000100fd, 0x000200f8, 0x0000004c,
    0x0004003d, 0x0000004f, 0x00000052, 0x00000051,
    0x0004003d, 0x00000006, 0x00000053, 0x0000002d,
    0x00050084, 0x00000006, 0x00000055, 0x00000053,
    0x00000054, 0x00050080, 0x00000006, 0x00000056,
    0x00000055, 0x00000019, 0x0004007c, 0x00000008,
    0x00000057, 0x00000056, 0x00050062, 0x00000058,
    0x00000059, 0x00000052, 0x00000057, 0x00050051,
    0x00000006, 0x0000005a, 0x00000059, 0x00000000,
    0x0003003e, 0x0000004e, 0x0000005a, 0x0004003d,
    0x0000004f, 0x0000005c, 0x00000051, 0x0004003d,
    0x00000006, 0x0000005d, 0x0000002d, 0x00050084,
    0x00000006, 0x0000005e, 0x0000005d, 0x00000054,
    0x00050080, 0x00000006, 0x0000005f, 0x0000005e,
    0x0000001d, 0x0004007c, 0x00000008, 0x00000060,
    0x0000005f, 0x00050062, 0x00000058, 0x00000061,
    0x0000005c, 0x00000060, 0x00050051, 0x00000006,
    0x00000062, 0x00000061, 0x00000000, 0x0003003e,
    0x0000005b, 0x00000062, 0x0004003d, 0x0000004f,
    0x00000064, 0x00000051, 0x0004003d, 0x00000006,
    0x00000065, 0x0000002d, 0x00050084, 0x00000006,
    0x00000066, 0x00000065, 0x00000054, 0x00050080,
    0x00000006, 0x00000068, 0x00000066, 0x00000067,
    0x0004007c, 0x00000008, 0x00000069, 0x00000068,
    0x00050062, 0x00000058, 0x0000006a, 0x00000064,
    0x00000069, 0x00050051, 0x00000006, 0x0000006b,
    0x0000006a, 0x00000000, 0x0003003e, 0x00000063,
    0x0000006b, 0x0004003d, 0x0000004f, 0x0000006d,
    0x00000051, 0x0004003d, 0x00000006, 0x0000006e,
    0x0000002d, 0x00050084, 0x00000006, 0x0000006f,
    0x0000006e, 0x00000054, 0x00050080, 0x00000006,
    0x00000070, 0x0000006f, 0x00000045, 0x0004007c,
    0x00000008, 0x00000071, 0x00000070, 0x00050062,
    0x00000058, 0x00000072, 0x0000006d, 0x00000071,
    0x00050051, 0x00000006, 0x00000073, 0x00000072,
    0x00000000, 0x0003003e, 0x0000006c, 0x00000073,
    0x0004003d, 0x0000004f, 0x00000075, 0x00000051,
    0x0004003d, 0x00000006, 0x00000076, 0x0000002d,
    0x00050084, 0x00000006, 0x00000077, 0x00000076,
    0x00000054, 0x00050080, 0x00000006, 0x00000079,
    0x00000077, 0x00000078, 0x0004007c, 0x00000008,
    0x0000007a, 0x00000079, 0x00050062, 0x00000058,
    0x0000007b, 0x00000075, 0x0000007a, 0x00050051,
    0x00000006, 0x0000007c, 0x0000007b, 0x00000000,
    0x0003003e, 0x00000074, 0x0000007c, 0x0004003d,
    0x0000004f, 0x0000007e, 0x00000051, 0x0004003d,
    0x00000006, 0x0000007f, 0x0000002d, 0x00050084,
    0x00000006, 0x00000080, 0x0000007f, 0x00000054,
    0x00050080, 0x00000006, 0x00000082, 0x00000080,
    0x00000081, 0x0004007c, 0x00000008, 0x00000083,
    0x00000082, 0x00050062, 0x00000058, 0x00000084,
    0x0000007e, 0x00000083, 0x00050051, 0x00000006,
    0x00000085, 0x00000084, 0x00000000, 0x0003003e,
    0x0000007d, 0x00000085, 0x0004003d, 0x00000006,
    0x00000087, 0x0000004e, 0x0003003e, 0x00000086,
    0x00000087, 0x000200f9, 0x00000088, 0x000200f8,
    0x00000088, 0x000400f6, 0x0000008a, 0x0000008b,
    0x00000000, 0x000200f9, 0x0000008c, 0x000200f8,
    0x0000008c, 0x0004003d, 0x00000006, 0x0000008d,
    0x00000086, 0x0004003d, 0x00000006, 0x0000008e,
    0x0000006c, 0x000500b2, 0x00000038, 0x0000008f,
    0x0000008d, 0x0000008e, 0x000400fa, 0x0000008f,
    0x00000089, 0x0000008a, 0x000200f8, 0x00000089,
    0x0004003d, 0x00000006, 0x00000091, 0x0000005b,
    0x0003003e, 0x00000090, 0x00000091, 0x000200f9,
    0x00000092, 0x000200f8, 0x00000092, 0x000400f6,
    0x00000094, 0x00000095, 0x00000000, 0x000200f9,
    0x00000096, 0x000200f8, 0x00000096, 0x0004003d,
    0x00000006, 0x00000097, 0x00000090, 0x0004003d,
    0x00000006, 0x00000098, 0x00000074, 0x000500b2,
    0x00000038, 0x00000099, 0x00000097, 0x00000098,
    0x000400fa, 0x00000099, 0x00000093, 0x00000094,
    0x000200f8, 0x00000093, 0x0004003d, 0x00000006,
    0x0000009b, 0x00000063, 0x0003003e, 0x0000009a,
    0x0000009b, 0x000200f9, 0x0000009c, 0x000200f8,
    0x0000009c, 0x000400f6, 0x0000009e, 0x0000009f,
    0x00000000, 0x000200f9, 0x000000a0, 0x000200f8,
    0x000000a0, 0x0004003d, 0x00000006, 0x000000a1,
    0x0000009a, 0x0004003d, 0x00000006, 0x000000a2,
    0x0000007d, 0x000500b2, 0x00000038, 0x000000a3,
    0x000000a1, 0x000000a2, 0x000400fa, 0x000000a3,
    0x0000009d, 0x0000009e, 0x000200f8, 0x0000009d,
    0x0004003d, 0x00000006, 0x000000a7, 0x00000086,
    0x0003003e, 0x000000a6, 0x000000a7, 0x0004003d,
    0x00000006, 0x000000a9, 0x00000090, 0x0003003e,
    0x000000a8, 0x000000a9, 0x0004003d, 0x00000006,
    0x000000ab, 0x0000009a, 0x0003003e, 0x000000aa,
    0x000000ab, 0x00070039, 0x00000008, 0x000000ac,
    0x0000000d, 0x000000a6, 0x000000a8, 0x000000aa,
    0x0003003e, 0x000000a5, 0x000000ac, 0x0004003d,
    0x000000ad, 0x000000b0, 0x000000af, 0x0004003d,
    0x00000008, 0x000000b1, 0x000000a5, 0x00050062,
    0x00000058, 0x000000b2, 0x000000b0, 0x000000b1,
    0x00050051, 0x00000006, 0x000000b3, 0x000000b2,
    0x00000000, 0x000500aa, 0x00000038, 0x000000b4,
    0x000000b3, 0x0000001d, 0x000300f7, 0x000000b6,
    0x00000000, 0x000400fa, 0x000000b4, 0x000000b5,
    0x000000b6, 0x000200f8, 0x000000b5, 0x0004003d,
    0x0000004f, 0x000000b9, 0x000000b8, 0x0004003d,
    0x00000008, 0x000000ba, 0x000000a5, 0x00050062,
    0x00000058, 0x000000bb, 0x000000b9, 0x000000ba,
    0x00050051, 0x00000006, 0x000000bc, 0x000000bb,
    0x00000000, 0x0003003e, 0x000000b7, 0x000000bc,
    0x0004003d, 0x00000008, 0x000000bf, 0x000000a5,
    0x0006003c, 0x000000c0, 0x000000c1, 0x000000be,
    0x000000bf, 0x00000019, 0x000700ea, 0x00000006,
    0x000000c2, 0x000000c1, 0x0000001d, 0x00000019,
    0x0000001d, 0x0003003e, 0x000000bd, 0x000000c2,
    0x0004003d, 0x0000004f, 0x000000c4, 0x000000c3,
    0x0004003d, 0x00000006, 0x000000c5, 0x000000b7,
    0x0004003d, 0x00000006, 0x000000c6, 0x000000bd,
    0x00050080, 0x00000006, 0x000000c7, 0x000000c5,
    0x000000c6, 0x0004007c, 0x00000008, 0x000000c8,
    0x000000c7, 0x0004003d, 0x00000006, 0x000000c9,
    0x0000002d, 0x00070050, 0x00000058, 0x000000ca,
    0x000000c9, 0x00000019, 0x00000019, 0x00000019,
    0x00040063, 0x000000c4, 0x000000c8, 0x000000ca,
    0x000200f9, 0x000000b6, 0x000200f8, 0x000000b6,
    0x000200f9, 0x0000009f, 0x000200f8, 0x0000009f,
    0x0004003d, 0x00000006, 0x000000cb, 0x0000009a,
    0x00050080, 0x00000006, 0x000000cd, 0x000000cb,
    0x000000cc, 0x0003003e, 0x0000009a, 0x000000cd,
    0x000200f9, 0x0000009c, 0x000200f8, 0x0000009e,
    0x000200f9, 0x00000095, 0x000200f8, 0x00000095,
    0x0004003d, 0x00000006, 0x000000ce, 0x00000090,
    0x00050080, 0x00000006, 0x000000cf, 0x000000ce,
    0x000000cc, 0x0003003e, 0x00000090, 0x000000cf,
    0x000200f9, 0x00000092, 0x000200f8, 0x00000094,
    0x000200f9, 0x0000008b, 0x000200f8, 0x0000008b,
    0x0004003d, 0x00000006, 0x000000d0, 0x00000086,
    0x00050080, 0x00000006, 0x000000d1, 0x000000d0,
    0x000000cc, 0x0003003e, 0x00000086, 0x000000d1,
    0x000200f9, 0x00000088, 0x000200f8, 0x0000008a,
    0x000200f9, 0x0000003b, 0x000200f8, 0x0000003b,
    0x000100fd, 0x00010038, 0x00050036, 0x00000008,
    0x0000000d, 0x00000000, 0x00000009, 0x00030037,
    0x00000007, 0x0000000a, 0x00030037, 0x00000007,
    0x0000000b, 0x00030037, 0x00000007, 0x0000000c,
    0x000200f8, 0x0000000e, 0x00060041, 0x0000001a,
    0x0000001b, 0x00000017, 0x00000018, 0x00000019,
    0x0004003d, 0x00000006, 0x0000001c, 0x0000001b,
    0x00060041, 0x0000001a, 0x0000001e, 0x00000017,
    0x00000018, 0x0000001d, 0x0004003d, 0x00000006,
    0x0000001f, 0x0000001e, 0x00050084, 0x00000006,
    0x00000020, 0x0000001c, 0x0000001f, 0x0004003d,
    0x00000006, 0x00000021, 0x0000000c, 0x00050084,
    0x00000006, 0x00000022, 0x00000020, 0x00000021,
    0x00060041, 0x0000001a, 0x00000023, 0x00000017,
    0x00000018, 0x00000019, 0x0004003d, 0x00000006,
    0x00000024, 0x00000023, 0x0004003d, 0x00000006,
    0x00000025, 0x0000000b, 0x00050084, 0x00000006,
    0x00000026, 0x00000024, 0x00000025, 0x00050080,
    0x00000006, 0x00000027, 0x00000022, 0x00000026,
    0x0004003d, 0x00000006, 0x00000028, 0x0000000a,
    0x00050080, 0x00000006, 0x00000029, 0x00000027,
    0x00000028, 0x0004007c, 0x00000008, 0x0000002a,
    0x00000029, 0x000200fe, 0x0000002a, 0x00010038,
};
