#include <stdint.h>

#if 0
C:/msys64/home/sydlu/CProjects/clustered-forward-demo-vk/demo/clustering.frag
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 121

                              Capability Shader
                              Capability ImageBuffer
                              Capability StorageImageExtendedFormats
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 99 103
                              ExecutionMode 4 OriginUpperLeft
                              ExecutionMode 4 EarlyFragmentTests
                              Source GLSL 450
                              Name 4  "main"
                              Name 15  "view_pos_to_grid_coord(vf2;f1;"
                              Name 13  "frag_pos"
                              Name 14  "view_z"
                              Name 20  "grid_coord_to_grid_idx(vu3;"
                              Name 19  "c"
                              Name 24  "c"
                              Name 32  "UBO"
                              MemberName 32(UBO) 0  "view"
                              MemberName 32(UBO) 1  "normal"
                              MemberName 32(UBO) 2  "model"
                              MemberName 32(UBO) 3  "projection_clip"
                              MemberName 32(UBO) 4  "tile_size"
                              MemberName 32(UBO) 5  "grid_dim"
                              MemberName 32(UBO) 6  "cam_pos"
                              MemberName 32(UBO) 7  "cam_far"
                              MemberName 32(UBO) 8  "resolution"
                              MemberName 32(UBO) 9  "num_lights"
                              Name 34  "ubo_in"
                              Name 93  "view_pos"
                              Name 99  "world_pos_in"
                              Name 102  "grid_idx"
                              Name 103  "gl_FragCoord"
                              Name 104  "param"
                              Name 107  "param"
                              Name 111  "param"
                              Name 115  "grid_flags"
                              MemberDecorate 32(UBO) 0 ColMajor
                              MemberDecorate 32(UBO) 0 Offset 0
                              MemberDecorate 32(UBO) 0 MatrixStride 16
                              MemberDecorate 32(UBO) 1 ColMajor
                              MemberDecorate 32(UBO) 1 Offset 64
                              MemberDecorate 32(UBO) 1 MatrixStride 16
                              MemberDecorate 32(UBO) 2 ColMajor
                              MemberDecorate 32(UBO) 2 Offset 128
                              MemberDecorate 32(UBO) 2 MatrixStride 16
                              MemberDecorate 32(UBO) 3 ColMajor
                              MemberDecorate 32(UBO) 3 Offset 192
                              MemberDecorate 32(UBO) 3 MatrixStride 16
                              MemberDecorate 32(UBO) 4 Offset 256
                              MemberDecorate 32(UBO) 5 Offset 264
                              MemberDecorate 32(UBO) 6 Offset 272
                              MemberDecorate 32(UBO) 7 Offset 284
                              MemberDecorate 32(UBO) 8 Offset 288
                              MemberDecorate 32(UBO) 9 Offset 296
                              Decorate 32(UBO) Block
                              Decorate 34(ubo_in) DescriptorSet 0
                              Decorate 34(ubo_in) Binding 0
                              Decorate 99(world_pos_in) Location 0
                              Decorate 103(gl_FragCoord) BuiltIn FragCoord
                              Decorate 115(grid_flags) DescriptorSet 1
                              Decorate 115(grid_flags) Binding 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 2
               8:             TypePointer Function 7(fvec2)
               9:             TypePointer Function 6(float)
              10:             TypeInt 32 0
              11:             TypeVector 10(int) 3
              12:             TypeFunction 11(ivec3) 8(ptr) 9(ptr)
              17:             TypePointer Function 11(ivec3)
              18:             TypeFunction 10(int) 17(ptr)
              22:             TypeVector 6(float) 3
              23:             TypePointer Function 22(fvec3)
              26:    6(float) Constant 1056964608
              29:             TypeVector 6(float) 4
              30:             TypeMatrix 29(fvec4) 4
              31:             TypeVector 10(int) 2
         32(UBO):             TypeStruct 30 30 30 30 7(fvec2) 31(ivec2) 22(fvec3) 6(float) 7(fvec2) 10(int)
              33:             TypePointer Uniform 32(UBO)
      34(ubo_in):     33(ptr) Variable Uniform
              35:             TypeInt 32 1
              36:     35(int) Constant 4
              37:             TypePointer Uniform 7(fvec2)
              43:    6(float) Constant 1132396544
              44:    6(float) Constant 0
              45:    6(float) Constant 1132462080
              48:    6(float) Constant 1036831949
              50:     35(int) Constant 7
              51:             TypePointer Uniform 6(float)
              56:    6(float) Constant 1065353216
              62:     10(int) Constant 2
              68:     35(int) Constant 5
              69:     10(int) Constant 0
              70:             TypePointer Uniform 10(int)
              73:     10(int) Constant 1
              77:             TypePointer Function 10(int)
              92:             TypePointer Function 29(fvec4)
              94:     35(int) Constant 0
              95:             TypePointer Uniform 30
              98:             TypePointer Input 29(fvec4)
99(world_pos_in):     98(ptr) Variable Input
103(gl_FragCoord):     98(ptr) Variable Input
             113:             TypeImage 10(int) Buffer nonsampled format:R8ui
             114:             TypePointer UniformConstant 113
 115(grid_flags):    114(ptr) Variable UniformConstant
             119:             TypeVector 10(int) 4
             120:  119(ivec4) ConstantComposite 73 69 69 69
         4(main):           2 Function None 3
               5:             Label
    93(view_pos):     92(ptr) Variable Function
   102(grid_idx):     77(ptr) Variable Function
      104(param):      8(ptr) Variable Function
      107(param):      9(ptr) Variable Function
      111(param):     17(ptr) Variable Function
              96:     95(ptr) AccessChain 34(ubo_in) 94
              97:          30 Load 96
             100:   29(fvec4) Load 99(world_pos_in)
             101:   29(fvec4) MatrixTimesVector 97 100
                              Store 93(view_pos) 101
             105:   29(fvec4) Load 103(gl_FragCoord)
             106:    7(fvec2) VectorShuffle 105 105 0 1
                              Store 104(param) 106
             108:      9(ptr) AccessChain 93(view_pos) 62
             109:    6(float) Load 108
                              Store 107(param) 109
             110:   11(ivec3) FunctionCall 15(view_pos_to_grid_coord(vf2;f1;) 104(param) 107(param)
                              Store 111(param) 110
             112:     10(int) FunctionCall 20(grid_coord_to_grid_idx(vu3;) 111(param)
                              Store 102(grid_idx) 112
             116:         113 Load 115(grid_flags)
             117:     10(int) Load 102(grid_idx)
             118:     35(int) Bitcast 117
                              ImageWrite 116 118 120
                              Return
                              FunctionEnd
15(view_pos_to_grid_coord(vf2;f1;):   11(ivec3) Function None 12
    13(frag_pos):      8(ptr) FunctionParameter
      14(view_z):      9(ptr) FunctionParameter
              16:             Label
           24(c):     23(ptr) Variable Function
              25:    7(fvec2) Load 13(frag_pos)
              27:    7(fvec2) CompositeConstruct 26 26
              28:    7(fvec2) FSub 25 27
              38:     37(ptr) AccessChain 34(ubo_in) 36
              39:    7(fvec2) Load 38
              40:    7(fvec2) FDiv 28 39
              41:   22(fvec3) Load 24(c)
              42:   22(fvec3) VectorShuffle 41 40 3 4 2
                              Store 24(c) 42
              46:    6(float) Load 14(view_z)
              47:    6(float) FNegate 46
              49:    6(float) FSub 47 48
              52:     51(ptr) AccessChain 34(ubo_in) 50
              53:    6(float) Load 52
              54:    6(float) FSub 53 48
              55:    6(float) FDiv 49 54
              57:    6(float) FAdd 55 56
              58:    6(float) ExtInst 1(GLSL.std.450) 28(Log) 57
              59:    6(float) FMul 45 58
              60:    6(float) ExtInst 1(GLSL.std.450) 40(FMax) 44 59
              61:    6(float) ExtInst 1(GLSL.std.450) 37(FMin) 43 60
              63:      9(ptr) AccessChain 24(c) 62
                              Store 63 61
              64:   22(fvec3) Load 24(c)
              65:   11(ivec3) ConvertFToU 64
                              ReturnValue 65
                              FunctionEnd
20(grid_coord_to_grid_idx(vu3;):     10(int) Function None 18
           19(c):     17(ptr) FunctionParameter
              21:             Label
              71:     70(ptr) AccessChain 34(ubo_in) 68 69
              72:     10(int) Load 71
              74:     70(ptr) AccessChain 34(ubo_in) 68 73
              75:     10(int) Load 74
              76:     10(int) IMul 72 75
              78:     77(ptr) AccessChain 19(c) 62
              79:     10(int) Load 78
              80:     10(int) IMul 76 79
              81:     70(ptr) AccessChain 34(ubo_in) 68 69
              82:     10(int) Load 81
              83:     77(ptr) AccessChain 19(c) 73
              84:     10(int) Load 83
              85:     10(int) IMul 82 84
              86:     10(int) IAdd 80 85
              87:     77(ptr) AccessChain 19(c) 69
              88:     10(int) Load 87
              89:     10(int) IAdd 86 88
                              ReturnValue 89
                              FunctionEnd
#endif

static const uint32_t clustering_frag[835] = {
    0x07230203, 0x00010000, 0x00080001, 0x00000079,
    0x00000000, 0x00020011, 0x00000001, 0x00020011,
    0x0000002f, 0x00020011, 0x00000031, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0007000f, 0x00000004, 0x00000004, 0x6e69616d,
    0x00000000, 0x00000063, 0x00000067, 0x00030010,
    0x00000004, 0x00000007, 0x00030010, 0x00000004,
    0x00000009, 0x00030003, 0x00000002, 0x000001c2,
    0x00040005, 0x00000004, 0x6e69616d, 0x00000000,
    0x000a0005, 0x0000000f, 0x77656976, 0x736f705f,
    0x5f6f745f, 0x64697267, 0x6f6f635f, 0x76286472,
    0x663b3266, 0x00003b31, 0x00050005, 0x0000000d,
    0x67617266, 0x736f705f, 0x00000000, 0x00040005,
    0x0000000e, 0x77656976, 0x00007a5f, 0x00090005,
    0x00000014, 0x64697267, 0x6f6f635f, 0x745f6472,
    0x72675f6f, 0x695f6469, 0x76287864, 0x003b3375,
    0x00030005, 0x00000013, 0x00000063, 0x00030005,
    0x00000018, 0x00000063, 0x00030005, 0x00000020,
    0x004f4255, 0x00050006, 0x00000020, 0x00000000,
    0x77656976, 0x00000000, 0x00050006, 0x00000020,
    0x00000001, 0x6d726f6e, 0x00006c61, 0x00050006,
    0x00000020, 0x00000002, 0x65646f6d, 0x0000006c,
    0x00070006, 0x00000020, 0x00000003, 0x6a6f7270,
    0x69746365, 0x635f6e6f, 0x0070696c, 0x00060006,
    0x00000020, 0x00000004, 0x656c6974, 0x7a69735f,
    0x00000065, 0x00060006, 0x00000020, 0x00000005,
    0x64697267, 0x6d69645f, 0x00000000, 0x00050006,
    0x00000020, 0x00000006, 0x5f6d6163, 0x00736f70,
    0x00050006, 0x00000020, 0x00000007, 0x5f6d6163,
    0x00726166, 0x00060006, 0x00000020, 0x00000008,
    0x6f736572, 0x6974756c, 0x00006e6f, 0x00060006,
    0x00000020, 0x00000009, 0x5f6d756e, 0x6867696c,
    0x00007374, 0x00040005, 0x00000022, 0x5f6f6275,
    0x00006e69, 0x00050005, 0x0000005d, 0x77656976,
    0x736f705f, 0x00000000, 0x00060005, 0x00000063,
    0x6c726f77, 0x6f705f64, 0x6e695f73, 0x00000000,
    0x00050005, 0x00000066, 0x64697267, 0x7864695f,
    0x00000000, 0x00060005, 0x00000067, 0x465f6c67,
    0x43676172, 0x64726f6f, 0x00000000, 0x00040005,
    0x00000068, 0x61726170, 0x0000006d, 0x00040005,
    0x0000006b, 0x61726170, 0x0000006d, 0x00040005,
    0x0000006f, 0x61726170, 0x0000006d, 0x00050005,
    0x00000073, 0x64697267, 0x616c665f, 0x00007367,
    0x00040048, 0x00000020, 0x00000000, 0x00000005,
    0x00050048, 0x00000020, 0x00000000, 0x00000023,
    0x00000000, 0x00050048, 0x00000020, 0x00000000,
    0x00000007, 0x00000010, 0x00040048, 0x00000020,
    0x00000001, 0x00000005, 0x00050048, 0x00000020,
    0x00000001, 0x00000023, 0x00000040, 0x00050048,
    0x00000020, 0x00000001, 0x00000007, 0x00000010,
    0x00040048, 0x00000020, 0x00000002, 0x00000005,
    0x00050048, 0x00000020, 0x00000002, 0x00000023,
    0x00000080, 0x00050048, 0x00000020, 0x00000002,
    0x00000007, 0x00000010, 0x00040048, 0x00000020,
    0x00000003, 0x00000005, 0x00050048, 0x00000020,
    0x00000003, 0x00000023, 0x000000c0, 0x00050048,
    0x00000020, 0x00000003, 0x00000007, 0x00000010,
    0x00050048, 0x00000020, 0x00000004, 0x00000023,
    0x00000100, 0x00050048, 0x00000020, 0x00000005,
    0x00000023, 0x00000108, 0x00050048, 0x00000020,
    0x00000006, 0x00000023, 0x00000110, 0x00050048,
    0x00000020, 0x00000007, 0x00000023, 0x0000011c,
    0x00050048, 0x00000020, 0x00000008, 0x00000023,
    0x00000120, 0x00050048, 0x00000020, 0x00000009,
    0x00000023, 0x00000128, 0x00030047, 0x00000020,
    0x00000002, 0x00040047, 0x00000022, 0x00000022,
    0x00000000, 0x00040047, 0x00000022, 0x00000021,
    0x00000000, 0x00040047, 0x00000063, 0x0000001e,
    0x00000000, 0x00040047, 0x00000067, 0x0000000b,
    0x0000000f, 0x00040047, 0x00000073, 0x00000022,
    0x00000001, 0x00040047, 0x00000073, 0x00000021,
    0x00000000, 0x00020013, 0x00000002, 0x00030021,
    0x00000003, 0x00000002, 0x00030016, 0x00000006,
    0x00000020, 0x00040017, 0x00000007, 0x00000006,
    0x00000002, 0x00040020, 0x00000008, 0x00000007,
    0x00000007, 0x00040020, 0x00000009, 0x00000007,
    0x00000006, 0x00040015, 0x0000000a, 0x00000020,
    0x00000000, 0x00040017, 0x0000000b, 0x0000000a,
    0x00000003, 0x00050021, 0x0000000c, 0x0000000b,
    0x00000008, 0x00000009, 0x00040020, 0x00000011,
    0x00000007, 0x0000000b, 0x00040021, 0x00000012,
    0x0000000a, 0x00000011, 0x00040017, 0x00000016,
    0x00000006, 0x00000003, 0x00040020, 0x00000017,
    0x00000007, 0x00000016, 0x0004002b, 0x00000006,
    0x0000001a, 0x3f000000, 0x00040017, 0x0000001d,
    0x00000006, 0x00000004, 0x00040018, 0x0000001e,
    0x0000001d, 0x00000004, 0x00040017, 0x0000001f,
    0x0000000a, 0x00000002, 0x000c001e, 0x00000020,
    0x0000001e, 0x0000001e, 0x0000001e, 0x0000001e,
    0x00000007, 0x0000001f, 0x00000016, 0x00000006,
    0x00000007, 0x0000000a, 0x00040020, 0x00000021,
    0x00000002, 0x00000020, 0x0004003b, 0x00000021,
    0x00000022, 0x00000002, 0x00040015, 0x00000023,
    0x00000020, 0x00000001, 0x0004002b, 0x00000023,
    0x00000024, 0x00000004, 0x00040020, 0x00000025,
    0x00000002, 0x00000007, 0x0004002b, 0x00000006,
    0x0000002b, 0x437f0000, 0x0004002b, 0x00000006,
    0x0000002c, 0x00000000, 0x0004002b, 0x00000006,
    0x0000002d, 0x43800000, 0x0004002b, 0x00000006,
    0x00000030, 0x3dcccccd, 0x0004002b, 0x00000023,
    0x00000032, 0x00000007, 0x00040020, 0x00000033,
    0x00000002, 0x00000006, 0x0004002b, 0x00000006,
    0x00000038, 0x3f800000, 0x0004002b, 0x0000000a,
    0x0000003e, 0x00000002, 0x0004002b, 0x00000023,
    0x00000044, 0x00000005, 0x0004002b, 0x0000000a,
    0x00000045, 0x00000000, 0x00040020, 0x00000046,
    0x00000002, 0x0000000a, 0x0004002b, 0x0000000a,
    0x00000049, 0x00000001, 0x00040020, 0x0000004d,
    0x00000007, 0x0000000a, 0x00040020, 0x0000005c,
    0x00000007, 0x0000001d, 0x0004002b, 0x00000023,
    0x0000005e, 0x00000000, 0x00040020, 0x0000005f,
    0x00000002, 0x0000001e, 0x00040020, 0x00000062,
    0x00000001, 0x0000001d, 0x0004003b, 0x00000062,
    0x00000063, 0x00000001, 0x0004003b, 0x00000062,
    0x00000067, 0x00000001, 0x00090019, 0x00000071,
    0x0000000a, 0x00000005, 0x00000000, 0x00000000,
    0x00000000, 0x00000002, 0x00000027, 0x00040020,
    0x00000072, 0x00000000, 0x00000071, 0x0004003b,
    0x00000072, 0x00000073, 0x00000000, 0x00040017,
    0x00000077, 0x0000000a, 0x00000004, 0x0007002c,
    0x00000077, 0x00000078, 0x00000049, 0x00000045,
    0x00000045, 0x00000045, 0x00050036, 0x00000002,
    0x00000004, 0x00000000, 0x00000003, 0x000200f8,
    0x00000005, 0x0004003b, 0x0000005c, 0x0000005d,
    0x00000007, 0x0004003b, 0x0000004d, 0x00000066,
    0x00000007, 0x0004003b, 0x00000008, 0x00000068,
    0x00000007, 0x0004003b, 0x00000009, 0x0000006b,
    0x00000007, 0x0004003b, 0x00000011, 0x0000006f,
    0x00000007, 0x00050041, 0x0000005f, 0x00000060,
    0x00000022, 0x0000005e, 0x0004003d, 0x0000001e,
    0x00000061, 0x00000060, 0x0004003d, 0x0000001d,
    0x00000064, 0x00000063, 0x00050091, 0x0000001d,
    0x00000065, 0x00000061, 0x00000064, 0x0003003e,
    0x0000005d, 0x00000065, 0x0004003d, 0x0000001d,
    0x00000069, 0x00000067, 0x0007004f, 0x00000007,
    0x0000006a, 0x00000069, 0x00000069, 0x00000000,
    0x00000001, 0x0003003e, 0x00000068, 0x0000006a,
    0x00050041, 0x00000009, 0x0000006c, 0x0000005d,
    0x0000003e, 0x0004003d, 0x00000006, 0x0000006d,
    0x0000006c, 0x0003003e, 0x0000006b, 0x0000006d,
    0x00060039, 0x0000000b, 0x0000006e, 0x0000000f,
    0x00000068, 0x0000006b, 0x0003003e, 0x0000006f,
    0x0000006e, 0x00050039, 0x0000000a, 0x00000070,
    0x00000014, 0x0000006f, 0x0003003e, 0x00000066,
    0x00000070, 0x0004003d, 0x00000071, 0x00000074,
    0x00000073, 0x0004003d, 0x0000000a, 0x00000075,
    0x00000066, 0x0004007c, 0x00000023, 0x00000076,
    0x00000075, 0x00040063, 0x00000074, 0x00000076,
    0x00000078, 0x000100fd, 0x00010038, 0x00050036,
    0x0000000b, 0x0000000f, 0x00000000, 0x0000000c,
    0x00030037, 0x00000008, 0x0000000d, 0x00030037,
    0x00000009, 0x0000000e, 0x000200f8, 0x00000010,
    0x0004003b, 0x00000017, 0x00000018, 0x00000007,
    0x0004003d, 0x00000007, 0x00000019, 0x0000000d,
    0x00050050, 0x00000007, 0x0000001b, 0x0000001a,
    0x0000001a, 0x00050083, 0x00000007, 0x0000001c,
    0x00000019, 0x0000001b, 0x00050041, 0x00000025,
    0x00000026, 0x00000022, 0x00000024, 0x0004003d,
    0x00000007, 0x00000027, 0x00000026, 0x00050088,
    0x00000007, 0x00000028, 0x0000001c, 0x00000027,
    0x0004003d, 0x00000016, 0x00000029, 0x00000018,
    0x0008004f, 0x00000016, 0x0000002a, 0x00000029,
    0x00000028, 0x00000003, 0x00000004, 0x00000002,
    0x0003003e, 0x00000018, 0x0000002a, 0x0004003d,
    0x00000006, 0x0000002e, 0x0000000e, 0x0004007f,
    0x00000006, 0x0000002f, 0x0000002e, 0x00050083,
    0x00000006, 0x00000031, 0x0000002f, 0x00000030,
    0x00050041, 0x00000033, 0x00000034, 0x00000022,
    0x00000032, 0x0004003d, 0x00000006, 0x00000035,
    0x00000034, 0x00050083, 0x00000006, 0x00000036,
    0x00000035, 0x00000030, 0x00050088, 0x00000006,
    0x00000037, 0x00000031, 0x00000036, 0x00050081,
    0x00000006, 0x00000039, 0x00000037, 0x00000038,
    0x0006000c, 0x00000006, 0x0000003a, 0x00000001,
    0x0000001c, 0x00000039, 0x00050085, 0x00000006,
    0x0000003b, 0x0000002d, 0x0000003a, 0x0007000c,
    0x00000006, 0x0000003c, 0x00000001, 0x00000028,
    0x0000002c, 0x0000003b, 0x0007000c, 0x00000006,
    0x0000003d, 0x00000001, 0x00000025, 0x0000002b,
    0x0000003c, 0x00050041, 0x00000009, 0x0000003f,
    0x00000018, 0x0000003e, 0x0003003e, 0x0000003f,
    0x0000003d, 0x0004003d, 0x00000016, 0x00000040,
    0x00000018, 0x0004006d, 0x0000000b, 0x00000041,
    0x00000040, 0x000200fe, 0x00000041, 0x00010038,
    0x00050036, 0x0000000a, 0x00000014, 0x00000000,
    0x00000012, 0x00030037, 0x00000011, 0x00000013,
    0x000200f8, 0x00000015, 0x00060041, 0x00000046,
    0x00000047, 0x00000022, 0x00000044, 0x00000045,
    0x0004003d, 0x0000000a, 0x00000048, 0x00000047,
    0x00060041, 0x00000046, 0x0000004a, 0x00000022,
    0x00000044, 0x00000049, 0x0004003d, 0x0000000a,
    0x0000004b, 0x0000004a, 0x00050084, 0x0000000a,
    0x0000004c, 0x00000048, 0x0000004b, 0x00050041,
    0x0000004d, 0x0000004e, 0x00000013, 0x0000003e,
    0x0004003d, 0x0000000a, 0x0000004f, 0x0000004e,
    0x00050084, 0x0000000a, 0x00000050, 0x0000004c,
    0x0000004f, 0x00060041, 0x00000046, 0x00000051,
    0x00000022, 0x00000044, 0x00000045, 0x0004003d,
    0x0000000a, 0x00000052, 0x00000051, 0x00050041,
    0x0000004d, 0x00000053, 0x00000013, 0x00000049,
    0x0004003d, 0x0000000a, 0x00000054, 0x00000053,
    0x00050084, 0x0000000a, 0x00000055, 0x00000052,
    0x00000054, 0x00050080, 0x0000000a, 0x00000056,
    0x00000050, 0x00000055, 0x00050041, 0x0000004d,
    0x00000057, 0x00000013, 0x00000045, 0x0004003d,
    0x0000000a, 0x00000058, 0x00000057, 0x00050080,
    0x0000000a, 0x00000059, 0x00000056, 0x00000058,
    0x000200fe, 0x00000059, 0x00010038,
};
