#include <stdint.h>

#if 0
C:/msys64/home/sydlu/CProjects/clustered-forward-demo-vk/demo/light_particles.frag
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 39

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 11 24 27
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 8  "r"
                              Name 11  "gl_PointCoord"
                              Name 24  "frag_color"
                              Name 27  "color_in"
                              Decorate 11(gl_PointCoord) BuiltIn PointCoord
                              Decorate 24(frag_color) Location 0
                              Decorate 27(color_in) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypePointer Function 6(float)
               9:             TypeVector 6(float) 2
              10:             TypePointer Input 9(fvec2)
11(gl_PointCoord):     10(ptr) Variable Input
              13:    6(float) Constant 1056964608
              14:    9(fvec2) ConstantComposite 13 13
              17:             TypeBool
              22:             TypeVector 6(float) 4
              23:             TypePointer Output 22(fvec4)
  24(frag_color):     23(ptr) Variable Output
              25:             TypeVector 6(float) 3
              26:             TypePointer Input 25(fvec3)
    27(color_in):     26(ptr) Variable Input
              29:    6(float) Constant 1082130432
              32:    6(float) Constant 1073741824
         4(main):           2 Function None 3
               5:             Label
            8(r):      7(ptr) Variable Function
              12:    9(fvec2) Load 11(gl_PointCoord)
              15:    6(float) ExtInst 1(GLSL.std.450) 67(Distance) 12 14
                              Store 8(r) 15
              16:    6(float) Load 8(r)
              18:    17(bool) FOrdGreaterThan 16 13
                              SelectionMerge 20 None
                              BranchConditional 18 19 20
              19:               Label
                                Kill
              20:             Label
              28:   25(fvec3) Load 27(color_in)
              30:    6(float) Load 8(r)
              31:    6(float) FSub 13 30
              33:    6(float) ExtInst 1(GLSL.std.450) 26(Pow) 31 32
              34:    6(float) FMul 29 33
              35:    6(float) CompositeExtract 28 0
              36:    6(float) CompositeExtract 28 1
              37:    6(float) CompositeExtract 28 2
              38:   22(fvec4) CompositeConstruct 35 36 37 34
                              Store 24(frag_color) 38
                              Return
                              FunctionEnd
#endif

static const uint32_t light_particles_frag[230] = {
    0x07230203, 0x00010000, 0x00080001, 0x00000027,
    0x00000000, 0x00020011, 0x00000001, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0008000f, 0x00000004, 0x00000004, 0x6e69616d,
    0x00000000, 0x0000000b, 0x00000018, 0x0000001b,
    0x00030010, 0x00000004, 0x00000007, 0x00030003,
    0x00000002, 0x000001c2, 0x00040005, 0x00000004,
    0x6e69616d, 0x00000000, 0x00030005, 0x00000008,
    0x00000072, 0x00060005, 0x0000000b, 0x505f6c67,
    0x746e696f, 0x726f6f43, 0x00000064, 0x00050005,
    0x00000018, 0x67617266, 0x6c6f635f, 0x0000726f,
    0x00050005, 0x0000001b, 0x6f6c6f63, 0x6e695f72,
    0x00000000, 0x00040047, 0x0000000b, 0x0000000b,
    0x00000010, 0x00040047, 0x00000018, 0x0000001e,
    0x00000000, 0x00040047, 0x0000001b, 0x0000001e,
    0x00000000, 0x00020013, 0x00000002, 0x00030021,
    0x00000003, 0x00000002, 0x00030016, 0x00000006,
    0x00000020, 0x00040020, 0x00000007, 0x00000007,
    0x00000006, 0x00040017, 0x00000009, 0x00000006,
    0x00000002, 0x00040020, 0x0000000a, 0x00000001,
    0x00000009, 0x0004003b, 0x0000000a, 0x0000000b,
    0x00000001, 0x0004002b, 0x00000006, 0x0000000d,
    0x3f000000, 0x0005002c, 0x00000009, 0x0000000e,
    0x0000000d, 0x0000000d, 0x00020014, 0x00000011,
    0x00040017, 0x00000016, 0x00000006, 0x00000004,
    0x00040020, 0x00000017, 0x00000003, 0x00000016,
    0x0004003b, 0x00000017, 0x00000018, 0x00000003,
    0x00040017, 0x00000019, 0x00000006, 0x00000003,
    0x00040020, 0x0000001a, 0x00000001, 0x00000019,
    0x0004003b, 0x0000001a, 0x0000001b, 0x00000001,
    0x0004002b, 0x00000006, 0x0000001d, 0x40800000,
    0x0004002b, 0x00000006, 0x00000020, 0x40000000,
    0x00050036, 0x00000002, 0x00000004, 0x00000000,
    0x00000003, 0x000200f8, 0x00000005, 0x0004003b,
    0x00000007, 0x00000008, 0x00000007, 0x0004003d,
    0x00000009, 0x0000000c, 0x0000000b, 0x0007000c,
    0x00000006, 0x0000000f, 0x00000001, 0x00000043,
    0x0000000c, 0x0000000e, 0x0003003e, 0x00000008,
    0x0000000f, 0x0004003d, 0x00000006, 0x00000010,
    0x00000008, 0x000500ba, 0x00000011, 0x00000012,
    0x00000010, 0x0000000d, 0x000300f7, 0x00000014,
    0x00000000, 0x000400fa, 0x00000012, 0x00000013,
    0x00000014, 0x000200f8, 0x00000013, 0x000100fc,
    0x000200f8, 0x00000014, 0x0004003d, 0x00000019,
    0x0000001c, 0x0000001b, 0x0004003d, 0x00000006,
    0x0000001e, 0x00000008, 0x00050083, 0x00000006,
    0x0000001f, 0x0000000d, 0x0000001e, 0x0007000c,
    0x00000006, 0x00000021, 0x00000001, 0x0000001a,
    0x0000001f, 0x00000020, 0x00050085, 0x00000006,
    0x00000022, 0x0000001d, 0x00000021, 0x00050051,
    0x00000006, 0x00000023, 0x0000001c, 0x00000000,
    0x00050051, 0x00000006, 0x00000024, 0x0000001c,
    0x00000001, 0x00050051, 0x00000006, 0x00000025,
    0x0000001c, 0x00000002, 0x00070050, 0x00000016,
    0x00000026, 0x00000023, 0x00000024, 0x00000025,
    0x00000022, 0x0003003e, 0x00000018, 0x00000026,
    0x000100fd, 0x00010038,
};
